#!/usr/bin/env python3
"""
Build the Cube FX simulator to WebAssembly.

    python build.py

The whole design rule here is that the simulator runs the SAME code the cube
runs, so anything it could get subtly wrong is taken from the firmware sources
rather than re-derived:

  * effects              compiled straight from usermods/cube_fx/
  * sin8_t / cos8_t      compiled from wled00/wled_math.cpp
  * scale8, qadd8, ...   compiled from fastled_slim.cpp
  * the 72 palettes     compiled from wled00/palettes.cpp
  * perlin noise         EXTRACTED from wled00/util.cpp at build time

That last one needs explaining. perlin8() lives in util.cpp, which drags in
Arduino, mbedtls and ESP headers and cannot be compiled on a host. But the noise
block itself is self-contained, so this script lifts exactly that block into a
generated file instead of hand-copying it. Hand-copying would work once and then
rot silently the first time upstream touched the noise - and since every
magnitude we tune (curl gain, densities, spin constants) is calibrated against
the noise field's actual shape, a stale copy would make the simulator confidently
wrong rather than obviously broken.
"""
import os, re, subprocess, sys, glob, json


def _procs():
    """native.procs (child processes with no console window), imported late:
    build.py is a script as well as a module, and runs from anywhere."""
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from native import procs
    return procs

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from native import paths                                   # noqa: E402
ROOT = paths.TREE                                          # None without a checkout: gen/ and runtime/ stand in
EMSDK = os.environ.get("EMSDK_ENV", r"C:\Users\seang\emsdk\emsdk_env.bat")

GEN = os.path.join(HERE, "gen")
os.makedirs(GEN, exist_ok=True)


def wasm_shell_command(line, emsdk_env, platform=None):
    """Prepare the Emscripten command for the current host shell.

    Windows needs emsdk_env.bat to populate cmd.exe's environment. On POSIX,
    setup-emsdk and normal emsdk installations expose em++ directly on PATH.
    """
    platform = platform or os.name
    if platform == "nt":
        return f'"{emsdk_env}" >nul 2>&1 && {line}'
    return line


def extract_palette_names():
    """Lift JSON_palette_names out of FX_fcn.cpp into gen/palette_names.json.

    The simulator used to carry its own six names, which meant its palette
    numbering and WLED's disagreed and every effect's pal= default previewed as
    the wrong colours. Taking the names from the same file the firmware serves
    them from is what keeps the two honest.
    """
    src = open(os.path.join(ROOT, "wled00", "FX_fcn.cpp"), encoding="utf-8",
               errors="surrogateescape").read()
    key = "const char JSON_palette_names[]"
    i = src.find(key)
    if i < 0:
        sys.exit("build: JSON_palette_names not found in FX_fcn.cpp")
    a = src.find("[", src.find('R"=====(', i))
    b = src.find("])=====", a)
    if a < 0 or b < 0:
        sys.exit("build: could not delimit JSON_palette_names")
    names = json.loads(src[a:b + 1])
    path = os.path.join(GEN, "palette_names.json")
    out = json.dumps(names, indent=1)
    prev = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if prev != out:
        open(path, "w", encoding="utf-8").write(out)
        print(f"  extracted {len(names)} palette names -> gen/palette_names.json")
    else:
        print(f"  palette names unchanged ({len(names)})")
    return names


def write_page_palettes(names):
    """Fill the browser page's palette selector from the firmware's own names.

    It used to hold six hand-written options whose values were the simulator's
    old ids, so picking "Rainbow" there asked for a palette that is now
    something else entirely. Generated, it cannot drift.

    Usermod-registered palettes are deliberately not listed: they only exist
    once the module has run setup(), so the page would have to ask the module
    at load time. The native app does that; the page shows the fixed set.
    """
    path = os.path.join(HERE, "index.html")
    src = open(path, encoding="utf-8").read()
    a = src.find("<!-- BEGIN PALETTE OPTIONS")
    b = src.find("<!-- END PALETTE OPTIONS", a)
    if a < 0 or b < 0:
        print("  page palettes: markers not found, skipping")
        return
    b = src.find("-->", b) + 3
    opts = []
    for i, n in enumerate(names):
        sel = " selected" if i == 11 else ""
        opts.append(f'<option value="{i}"{sel}>{n}</option>')
    block = ("<!-- BEGIN PALETTE OPTIONS (generated by build.py - do not edit) -->\n"
             '    <select id="pal">' + "".join(opts) + "</select></span>\n"
             "    <!-- END PALETTE OPTIONS -->")
    out = src[:a] + block + src[b:]
    if out != src:
        open(path, "w", encoding="utf-8", newline="\n").write(out)
        print(f"  page palette selector -> {len(names)} options")
    else:
        print("  page palette selector unchanged")


def extract_palettes():
    """Take wled00/palettes.cpp verbatim, swapping only its includes.

    The file is pure data - seven FastLED palettes and 59 cpt-city gradients -
    but it opens with #include "wled.h", and a quoted include resolves next to
    the file, so it drags in the real firmware header and every Arduino header
    behind it. Rewriting that one line is the whole adaptation; every byte of
    palette data is untouched, which is the point.
    """
    src = open(os.path.join(ROOT, "wled00", "palettes.cpp"), encoding="utf-8",
               errors="surrogateescape").read()
    if "gGradientPalettes[]" not in src:
        sys.exit("build: gGradientPalettes not found in palettes.cpp - has it moved?")
    body = src                                                     # its #include "wled.h" finds the shim's, on the include path
    body = body.replace('#include "src/dependencies/fastled_slim/fastled_slim.h"', '', 1)
    head = ["// GENERATED by build.py - do not edit.",
            "// wled00/palettes.cpp, verbatim apart from its include lines, so the",
            "// simulator's palettes are the exact bytes the firmware ships.",
            ""]
    out = "\n".join(head) + body + "\n"
    path = os.path.join(GEN, "wled_palettes.cpp")
    prev = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if prev != out:
        open(path, "w", encoding="utf-8").write(out)
        print("  extracted palettes -> gen/wled_palettes.cpp")
    else:
        print("  palettes unchanged")
    return path


def extract_noise():
    """Lift the self-contained Perlin block out of util.cpp."""
    src = open(os.path.join(ROOT, "wled00", "util.cpp"), encoding="utf-8",
               errors="surrogateescape").read()

    # Start at the PERLIN_SHIFT define, not at gradient1D: the gradient helpers
    # lean on it and on hashToGradient(), both of which sit just above.
    start = src.find("#define PERLIN_SHIFT")
    if start < 0:
        sys.exit("build: could not find PERLIN_SHIFT in util.cpp - has the noise moved?")

    end_marker = "uint8_t perlin8(uint16_t x, uint16_t y, uint16_t z)"
    end = src.find(end_marker)
    if end < 0:
        sys.exit("build: could not find perlin8(x,y,z) in util.cpp")
    end = src.find("}", src.find("{", end)) + 1

    body = src[start:end]
    out = ('// GENERATED by build.py - do not edit.\n'
           '// Lifted verbatim from wled00/util.cpp so the simulator\'s noise is\n'
           '// bit-for-bit the noise the firmware computes.\n'
           '#include "wled.h"\n\n' + body + "\n")
    path = os.path.join(GEN, "wled_noise.cpp")
    prev = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if prev != out:
        open(path, "w", encoding="utf-8").write(out)
        print(f"  extracted noise -> gen/wled_noise.cpp ({body.count(chr(10))} lines)")
    else:
        print("  noise unchanged")
    return path


# Stock WLED effects pulled in for side-by-side comparison. Each entry is
# (start marker, end marker, exported name). They are EXTRACTED rather than
# reimplemented for the same reason the noise is: a hand-written "equivalent"
# of Soap is precisely the thing that cannot settle an argument about whether
# ours matches it.
#
# Adding another is one line - find a self-contained mode_* in FX.cpp and name
# the first symbol above it that it depends on.
# Every 2-D effect in FX.cpp is pulled in, discovered rather than listed. The
# previous hand-written list held two of thirty-seven, which made "compare ours
# against WLED's" a much narrower claim than it sounded.
#
# Skipped, with the reason, because a simulator that silently omits things is
# worse than one that says what it left out:
STOCK_SKIP = {
    # Needs the font manager, the RTC and sprintf. None of that says anything
    # about how an effect looks on a cube.
    "mode_2Dscrollingtext": "needs fonts, the clock and printf",
    # Depends on a `Cell` struct declared at file scope in FX.cpp, well above
    # the effect bodies. Each span here runs from one effect to the next, so
    # anything declared before the first of them is out of reach. Pulling in
    # arbitrary file-scope declarations is a much larger change than this is
    # worth for one effect.
    "mode_2Dgameoflife": "needs a file-scope type the per-effect spans cannot reach",
}


def extract_span(src, a, b, what):
    i = src.find(a)
    if i < 0:
        sys.exit(f"build: could not find start of {what} ('{a}') in FX.cpp")
    j = src.find(b, i)
    if j < 0:
        sys.exit(f"build: could not find end of {what} ('{b}') in FX.cpp")
    return src[i:j]


def balance_conditionals(text):
    """Make a span's preprocessor directives self-contained.

    The 2-D effects sit inside `#ifndef WLED_DISABLE_2D` blocks that open and
    close around GROUPS of effects, so a span cut anywhere in the middle takes
    the `#if` without its `#endif` or the other way round. Either way clang
    reports an unterminated conditional and swallows every effect after it -
    three of them vanished that way while still being registered.

    Nothing here defines any of the WLED_DISABLE_* macros, so every one of these
    blocks is active regardless. Dropping an orphaned `#endif` and closing an
    unclosed `#if` therefore changes nothing about which code is compiled.
    """
    out, depth = [], 0
    for line in text.splitlines(keepends=True):
        st = line.lstrip()
        if st.startswith("#if"):
            depth += 1
        elif st.startswith("#endif"):
            if depth == 0:
                continue                      # orphan: its opener is elsewhere
            depth -= 1
        elif st.startswith(("#else", "#elif")) and depth == 0:
            continue
        out.append(line)
    return "".join(out) + ("\n#endif\n" * depth)


def discover_stock(fxsrc):
    """Find every 2-D effect in FX.cpp and lift it with its metadata string.

    Each effect is taken as the span from its own definition to the one after
    it, which sweeps up the file-static helpers that sit between them - the
    little per-effect functions like soapPixels that the effect cannot compile
    without and that nothing else references.
    """
    fn = re.compile(r"^\s*(?:static\s+)?(?:uint16_t|void)\s+(mode_2D\w+)\s*\([^)]*\)\s*\{",
                    re.M)
    hits = [(m.start(), m.group(1)) for m in fn.finditer(fxsrc)]
    if not hits:
        sys.exit("build: found no mode_2D* effects in FX.cpp - has the file moved?")

    # Each span runs from where the PREVIOUS one ended, not from the function
    # itself, so the declarations sitting between two effects come along with
    # the effect that needs them - `typedef struct Julia` six lines above
    # mode_2DJulia, `#define MAX_BEES 5` above the bees. Starting at the
    # function left those behind and the effects would not compile.
    # Metadata strings are collected SEPARATELY from bodies and emitted first.
    #
    # An earlier version carried each effect's metadata along inside its own
    # span and tracked where the last one ended. That bookkeeping was wrong
    # whenever a declaration sat in an unexpected place: three effects were
    # registered while their bodies had been trimmed off, so the file referred
    # to functions it did not contain. Collecting the two independently means a
    # body cannot be lost by a mistake about where its metadata was.
    #
    # The string literal must be matched AS a literal. Stopping at the first
    # semicolon truncates every one of them, since WLED's metadata format is
    # full of semicolons - "Black Hole@Fade rate,...,Blur;;!;2".
    LIT = r'\[\]\s*PROGMEM\s*=\s*"(?:[^"\\]|\\.)*"\s*;'
    bodies, metas, reg, skipped = [], [], [], []
    prev_end = hits[0][0]
    for k, (pos, name) in enumerate(hits):
        # Usually the symbol is the function name upper-cased, but not always:
        # mode_2Dfloatingblobs registers _data_FX_MODE_2DBLOBS. Guess first,
        # then fall back to whichever metadata declaration sits inside this
        # effect's own span - which is the one that belongs to it.
        sym = "_data_FX_MODE_" + name[len("mode_"):].upper()
        mm = re.search(r'static const char ' + sym + LIT, fxsrc)
        if not mm:
            span_end = hits[k + 1][0] if k + 1 < len(hits) else len(fxsrc)
            near = re.search(r'static const char (_data_FX_MODE_\w+)' + LIT,
                             fxsrc[pos:span_end])
            if near:
                sym = near.group(1)
                mm = re.search(r'static const char ' + sym + LIT, fxsrc)
        # The LAST effect must stop at its own metadata, not run to the end of
        # the file. Letting it run swept in every particle-system effect that
        # follows the 2-D block, and the build then failed asking for the whole
        # ParticleSystem2D library on behalf of an effect that never used it.
        if k + 1 < len(hits):
            end = hits[k + 1][0]
        else:
            end = mm.end() if (mm and mm.start() > pos) else len(fxsrc)
        # From where the last effect finished, so declarations sitting between
        # two effects come along with the one that needs them.
        body = fxsrc[prev_end:end]
        prev_end = end
        if name in STOCK_SKIP:
            skipped.append(name)
            continue
        if not mm:
            skipped.append(name + f" (no {sym})")
            continue
        # Strip metadata out of the body; it is emitted once, up front.
        bodies.append(balance_conditionals(
            re.sub(r'static const char _data_FX_MODE_\w+' + LIT, "", body)))
        metas.append(mm.group(0))
        reg.append((name, sym))
    for s in skipped:
        print(f"  stock: skipping {s} - {STOCK_SKIP.get(s, 'could not be isolated')}")
    return ["\n".join(metas) + "\n"] + bodies, reg


def extract_fx_modes():
    """Lift every #define FX_MODE_* out of FX.h into gen/fx_modes.h."""
    src = open(os.path.join(ROOT, "wled00", "FX.h"), encoding="utf-8",
               errors="surrogateescape").read()
    lines = [l for l in src.splitlines() if re.match(r"\s*#define\s+(FX_MODE_\w+|MODE_COUNT)\b", l)]
    out = ("// GENERATED by build.py from wled00/FX.h - do not edit.\n#pragma once\n"
           + "\n".join(lines) + "\n")
    path = os.path.join(GEN, "fx_modes.h")
    prev = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if prev != out:
        open(path, "w", encoding="utf-8").write(out)
        print(f"  extracted {len(lines)} FX_MODE ids -> gen/fx_modes.h")
    return path


def extract_stock():
    """Lift ColorFromPalette and the chosen stock effects out of the firmware."""
    colors = open(os.path.join(ROOT, "wled00", "colors.cpp"), encoding="utf-8",
                  errors="surrogateescape").read()
    cfp = extract_span(colors, "uint32_t ColorFromPalette(", "void setRandomColor(",
                       "ColorFromPalette")

    fxsrc = open(os.path.join(ROOT, "wled00", "FX.cpp"), encoding="utf-8",
                 errors="surrogateescape").read()
    parts, reg = discover_stock(fxsrc)

    # The roster is built here rather than in sim_main.cpp: the metadata strings
    # are static to this translation unit, and keeping the list beside the
    # extraction means it cannot fall out of step with what was extracted.
    reglines = "\n".join(f"  cfxBankAdd(&{fn}, {meta});" for fn, meta in reg)
    out = ('// GENERATED by build.py - do not edit.\n'
           '// Stock WLED code, lifted verbatim so comparisons are against the real\n'
           '// thing rather than against a paraphrase of it. Every 2-D effect in\n'
           '// FX.cpp is taken, discovered rather than listed.\n'
           '#include "wled.h"\n'
           '#include "cube_fx_bank.h"\n\n'
           + cfp + "\n" + "\n".join(parts) + "\n"
           "void simRegisterStock() {\n" + reglines + "\n}\n")
    path = os.path.join(GEN, "wled_fx.cpp")
    prev = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if prev != out:
        open(path, "w", encoding="utf-8").write(out)
        print(f"  extracted {len(reg)} stock 2-D effects + ColorFromPalette -> gen/wled_fx.cpp")
    else:
        print(f"  stock effects unchanged ({len(reg)})")
    return path


def find_vcvarsall():
    """Locate MSVC. vswhere is the supported way and survives version bumps."""
    pf = os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)")
    vswhere = os.path.join(pf, "Microsoft Visual Studio", "Installer", "vswhere.exe")
    if os.path.exists(vswhere):
        r = _procs().run([vswhere, "-latest", "-products", "*",
                            "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
                            "-property", "installationPath"],
                           capture_output=True, text=True)
        root = (r.stdout or "").strip().splitlines()
        if root:
            p = os.path.join(root[0], "VC", "Auxiliary", "Build", "vcvarsall.bat")
            if os.path.exists(p):
                return p
    for p in glob.glob(os.path.join(pf, "Microsoft Visual Studio", "*", "*",
                                    "VC", "Auxiliary", "Build", "vcvarsall.bat")):
        return p
    return None


def build_native(srcs, force=False):
    """Compile the same sources into a shared library the native front end loads.

    Delegated to native/toolchain.py, which compiles one object per translation
    unit with a cache and links a VERSIONED library - build/cubefx_<n>.dll -
    that the app can load while an older one is still open. The reasons for
    clang-not-MSVC (the VLA in CFX_NET_PREP) and for every flag are recorded
    there. cubefx.dll beside this script is still refreshed when it is not
    locked, so the CLI and older scripts keep working unchanged.
    """
    from native.toolchain import build_engine, lib_ext
    rep = build_engine(srcs, include_dirs(), force=force, log=print)
    if not rep.ok:
        print("  native: FAILED")
        return False
    legacy = os.path.join(HERE, "cubefx" + lib_ext())
    try:
        import shutil
        shutil.copyfile(rep.library, legacy)
    except OSError:
        print("  cubefx.dll is open in another process; build/latest points at the new one")
    return True


def engine_sources(extra=(), log=print):
    """Every translation unit the engine is made of - the extractions run
    first, so the generated files are current - plus any `extra` sources a
    project adds (the effects being edited in the studio). Without a WLED
    checkout the generated files in gen/ are taken as they are and the
    firmware files come from runtime/ (paths.py)."""
    fw = paths.firmware_dir()
    if ROOT:
        noise = extract_noise()
        extract_fx_modes()
        stock = extract_stock()
        write_page_palettes(extract_palette_names())
        from native.stock1d import extract as extract_stock1d
        stock1d = extract_stock1d(log=print)
        pal = extract_palettes()
    else:
        noise, stock, stock1d, pal = (os.path.join(GEN, f) for f in ("wled_noise.cpp", "wled_fx.cpp", "wled_fx1d.cpp", "wled_palettes.cpp"))
        missing = [p for p in (noise, stock, stock1d, pal) if not os.path.exists(p)] + ([] if os.path.isdir(fw) else [fw])
        if missing:
            sys.exit("build: no WLED checkout, and these are missing: " + ", ".join(missing) +
                     " - run  python build.py --runtime  from a checkout, or set WLED_ROOT")
        print("  no WLED checkout: gen/ and runtime/ as shipped")
    fx = sorted(glob.glob(os.path.join(fw, "cube_fx_[0-9][0-9]_*.cpp")))
    fx.append(os.path.join(fw, "cube_fx.cpp"))
    # Not an effect: registers audio-reactive palettes as a usermod. It has no NN
    # prefix so the glob above skips it, and it is named here explicitly.
    fx.append(os.path.join(fw, "cube_fx_palettes.cpp"))
    print(f"  {len(fx)} effect translation units")

    srcs = ([os.path.join(HERE, "sim_main.cpp")] + fx + [noise, stock, stock1d,
            paths.tree_path("wled00/wled_math.cpp"),
            # The real palette tables - seven FastLED palettes and 59 cpt-city
            # gradients - rather than a hand-copied handful. Compiling them is
            # what makes a palette id mean the same thing here as on the device.
            pal,
            paths.tree_path("wled00/src/dependencies/fastled_slim/fastled_slim.cpp")])
    return srcs + [os.path.abspath(e) for e in extra]


def include_dirs():
    """Where the engine's includes are found: the shim, the firmware, gen/,
    and FastLED's slim copy - by name, never by a path relative to the file."""
    return [os.path.join(HERE, "shim"), paths.firmware_dir(), GEN, paths.tree_path("wled00/src/dependencies/fastled_slim")]


def write_runtime(dest=None):
    """The firmware files the engine compiles from, copied out of the
    checkout into runtime/ (studio/runtime, or `dest`): what a packaged
    app builds effects from without a WLED tree beside it."""
    import shutil
    if not ROOT:
        sys.exit("build: --runtime needs a WLED checkout (the repo above studio/, or WLED_ROOT)")
    dest = dest or paths.RUNTIME
    for rel in paths.RUNTIME_FILES:
        src = os.path.join(ROOT, *rel.split("/"))
        dst = os.path.join(dest, *rel.split("/"))
        if os.path.isdir(src):
            if os.path.isdir(dst):
                shutil.rmtree(dst)
            shutil.copytree(src, dst, ignore=shutil.ignore_patterns("*.o", "*.pyc", "__pycache__"))
        else:
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copyfile(src, dst)
    n = sum(len(f) for _, _, f in os.walk(dest))
    print(f"  runtime: {n} files into {dest}")
    return dest


def main():
    want = set(sys.argv[1:]) or {"--wasm", "--native"}
    if "--wasm-only" in want:   want = {"--wasm"}
    if "--native-only" in want: want = {"--native"}
    if "--runtime" in want:                                # the firmware files out of the checkout, for a packaged app
        write_runtime(); return

    print("studio build")
    srcs = engine_sources()

    if "--native" in want:
        # The return value is NOT optional. build_native() reports a failure and
        # carries on, so ignoring it printed "build OK" over a link error and
        # left the PREVIOUS cubefx.dll in place - which then gets measured as
        # though it were the new code. The usual cause is the simulator app
        # holding the DLL open, so this is a routine failure, not a rare one.
        if not build_native(srcs, force=("--force" in sys.argv)):
            sys.exit("build FAILED - the dll was not replaced")
    if "--wasm" not in want:
        print("build OK")
        return

    # em++, not emcc. The simulator now holds std::vector palette registries
    # and a usermod list, and emcc links as C: the wasm link failed on
    # operator new, __cxa_throw and class vtables. emcc says so itself in
    # the failure - "try linking with em++ or passing -sDEFAULT_TO_CXX".
    cmd = ["em++", "-std=gnu++17", "-O2"]
    for d in include_dirs():                    # the same includes as the native build: the shim, the firmware, gen/, FastLED's slim copy
        cmd += ["-I", d]
    cmd += ["-DWLED_PS_DONT_REPLACE_2D_FX", "-DCFX_BANK_MAX_FX=256",
            "-DCFX_SIM"] + srcs + [
        "-o", "cubefx.js",
        # HEAPU8/HEAPU32 must be listed explicitly - current Emscripten does not
        # attach the heap views to the module by default, and reading pixels
        # back is the entire point of the exercise.
        "-s", "EXPORTED_RUNTIME_METHODS=ccall,cwrap,UTF8ToString,HEAPU8,HEAPU32",
        "-s", "ALLOW_MEMORY_GROWTH=1",
        "-s", "MODULARIZE=1",
        "-s", "EXPORT_NAME=CubeFX",
        "-s", "ENVIRONMENT=web",
    ]
    line = " ".join(f'"{c}"' if " " in c else c for c in cmd)

    # emsdk_env.bat needs SystemRoot and ComSpec, and some shells hand this
    # script an environment where they are EMPTY - Git Bash among them. The bat
    # then fails resolving %SystemRoot%\system32\..., and because the command is
    # chained with && that failure means emcc never runs at all. What you see is
    # "'emcc' is not recognized", which points at PATH and is the wrong trail
    # entirely: emsdk is installed and correct, and putting it on PATH does not
    # help, because the && still short-circuits on the bat.
    #
    # So the two are guaranteed here rather than assumed. Windows-only values,
    # applied only when missing.
    env = dict(os.environ)
    if not env.get("SystemRoot"):
        env["SystemRoot"] = os.environ.get("windir", r"C:\Windows")
    if not env.get("ComSpec"):
        env["ComSpec"] = os.path.join(env["SystemRoot"], "system32", "cmd.exe")

    # And MSYSTEM has to go. emsdk.py checks it (emsdk.py:99) and, seeing
    # MINGW64, writes the PATH it exports in POSIX form - "/c/Users/...", colon
    # separated. That is right for the bash that set it and wrong for the
    # cmd.exe the bat actually runs in, so emcc ends up on a PATH cmd cannot
    # read and `where emcc` returns nothing.
    #
    # Note this is NOT a PATH problem to be solved by converting PATH: Python
    # already holds a perfectly good Windows PATH, and rewriting it here only
    # corrupts it. What has to change is emsdk's idea of which shell it is
    # talking to.
    for k in ("MSYSTEM", "MSYS", "MSYSTEM_PREFIX"):
        env.pop(k, None)

    # Windows needs the batch file; on POSIX em++ is already on PATH.
    r = subprocess.run(wasm_shell_command(line, EMSDK), shell=True, cwd=HERE,
                       capture_output=True, text=True, env=env)
    if os.name == "nt" and r.returncode != 0 and "is not recognized" in ((r.stdout or "") + (r.stderr or "")):
        probe = subprocess.run(f'"{EMSDK}" && where emcc', shell=True, cwd=HERE,
                               capture_output=True, text=True, env=env)
        print("  emcc not found; emsdk_env.bat said:")
        print("   " + "\n   ".join(((probe.stdout or "") + (probe.stderr or "")).splitlines()[-6:]))
    out = (r.stdout or "") + (r.stderr or "")
    if r.returncode != 0:
        print(out[:4000]); sys.exit(f"build FAILED ({r.returncode})")
    if out.strip():
        print(out[:1500])
    for f in ("cubefx.js", "cubefx.wasm"):
        p = os.path.join(HERE, f)
        print(f"  {f}: {os.path.getsize(p):,} bytes" if os.path.exists(p) else f"  {f}: MISSING")
    print("build OK")


if __name__ == "__main__":
    main()
