"""Audio sync out (native/audio_sync.py): the packet as audioreactive lays it
out, and the sender - to this machine only (127.0.0.1, a free port): a test
never sends to the network's WLEDs.
Run with  python tests/test_audio_sync.py  (or pytest).
"""
import os
import socket
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))

import numpy as np                                     # noqa: E402
from native import audio_sync                          # noqa: E402


# AI: below section was generated by an AI
class _Eng:
    """What the sender reads from the engine."""
    def __init__(self):
        self.last_audio = (0.0, 0)
        self.last_peak = (0.0, 0.0)
        self.fft = np.zeros(16, np.uint8)


def _listener():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.bind(("127.0.0.1", 0))
    s.settimeout(2.0)
    return s, s.getsockname()[1]


def test_the_packet_is_audioreactives():
    """44 bytes, at the offsets audio_reactive.cpp's audioSyncPacket gives each field (its comments): the header
    at 0, sampleRaw 8, sampleSmth 12, samplePeak 16, fftResult 18, FFT_Magnitude 36, FFT_MajorPeak 40."""
    fft = list(range(0, 256, 16))
    p = audio_sync.packet(120.5, 99.0, True, fft, 812.0, 440.0)
    assert len(p) == 44
    assert p[:6] == b"00002\x00"
    assert struct.unpack_from("<f", p, 8)[0] == 99.0 and struct.unpack_from("<f", p, 12)[0] == 120.5
    assert p[16] == 1
    assert list(p[18:34]) == [min(254, b) for b in fft]          # the device sends 254 at most
    assert struct.unpack_from("<f", p, 36)[0] == 812.0 and struct.unpack_from("<f", p, 40)[0] == 440.0
    assert audio_sync.packet(-3, -1, False, [], 0, 0)[8:18] == bytes(10)  # nothing below zero, no bands: zeros
    back = audio_sync.unpack(p)
    assert back["volume"] == 120.5 and back["peak"] == 1 and back["major_peak"] == 440.0


def test_sent_at_its_rate_and_a_beat_kept():
    rx, port = _listener()
    tx = audio_sync.AudioSyncSender("unicast", host="http://127.0.0.1:80", port=port)
    try:
        eng = _Eng()
        eng.last_audio, eng.last_peak = (200.0, 0), (1261.0, 300.0)
        eng.fft[:] = np.arange(16) * 10
        assert tx.send(eng, now=10.0)
        got = audio_sync.unpack(rx.recv(64))
        assert got["volume"] == 200.0 and got["fft"][15] == 150 and got["major_peak"] == 1261.0 and got["peak"] == 0
        eng.last_audio = (180.0, 1)                                  # a beat, too soon after the last packet
        assert not tx.send(eng, now=10.005)
        eng.last_audio = (170.0, 0)
        assert tx.send(eng, now=10.0 + audio_sync.PERIOD * 1.01)            # the next packet carries it
        assert audio_sync.unpack(rx.recv(64))["peak"] == 1
        assert tx.send(eng, now=10.0 + audio_sync.PERIOD * 2.02)
        assert audio_sync.unpack(rx.recv(64))["peak"] == 0           # and only once
        assert tx.sent == 3 and "127.0.0.1" in tx.describe()
    finally:
        tx.close(); rx.close()


def test_the_modes():
    assert audio_sync.MODES[0] == "off"
    for bad in (("off", None), ("loud", None), ("unicast", None), ("unicast", "")):
        try:
            audio_sync.AudioSyncSender(*bad)
            assert False, bad
        except ValueError:
            pass
    tx = audio_sync.AudioSyncSender("multicast")                     # made, not used: nothing sent
    assert tx.addr == "239.0.0.1" and tx.port == 11988 and "multicast" in tx.describe()
    tx.close()
    assert audio_sync._host_only("http://10.0.0.5/") == "10.0.0.5" and audio_sync._host_only("10.0.0.5:80") == "10.0.0.5"
# AI: end


if __name__ == "__main__":
    import inspect
    bad = 0
    for name, fn in list(globals().items()):
        if name.startswith("test_") and inspect.isfunction(fn):
            try:
                fn(); print("ok  ", name)
            except Exception as ex:
                bad += 1; print("FAIL", name, repr(ex)[:3000])
    sys.exit(1 if bad else 0)
