#include "wled.h"
#include "cube_fx_common.h"
#include "cube_fx_bank.h"

// AI: below section was generated by an AI
// ===========================================================================
// Ace 3-D Jelly Bounce - jellies in a glass box, split by the kick
// ===========================================================================
// A handful of soft, glowing blobs live INSIDE the cube and are seen where they
// press against the glass. Each is a metaball - a field falling off as r^2/d^2
// from its centre (Jim Blinn's "blobby" model, "A Generalization of Algebraic
// Surface Drawing", ACM ToG 1982) - and the walls show the summed field, so two
// blobs that touch flow together into one shape instead of overlapping as
// discs. A blob far from every wall is invisible; one pressed against a wall
// is a big bright disc; one rolling over an edge wraps round it.
//
// They hug the glass: a gentle outward push, as if the box were spinning, so
// they spend their time rolling over the faces and bouncing off one another
// rather than hiding in the middle. Each one wobbles - its radius rings like
// a struck jelly after every impact, a damped spring - and the wall shows it.
//
// The playful part is the life cycle:
//   kick      SPLITS the biggest jelly in two: equal halves, half the volume
//             each, flung apart along a random line, in two new colours a
//             third of the palette either side of the parent's. A harder kick
//             flings them harder. Every jelly also gets a shove, so the whole
//             box jumps - the beat moves the jellies, it never flashes them.
//   merging   two jellies that meet slowly enough MERGE: the volumes add, and
//             the colour is the volume-weighted blend of the two palette
//             positions (blended round the palette circle, not in RGB, which
//             would turn two distant hues grey). So the box drifts back
//             towards a few big jellies until the next kick breaks one again.
//   mids      wobble: mid-band energy keeps every jelly quivering.
//   treble    a glint - the specular highlight on each jelly brightens.
//
// The shading is a jelly's: dark outside, a bright rim just inside the
// surface, a dimmer translucent body, and a white glint on the side facing
// the light. Black glass between them.
// ===========================================================================

#define JB_MAX     12
#define JB_MIN     2

struct JbBlob {
  float   x, y, z, vx, vy, vz;
  float   vol;                         // volume, r^3 up to a constant
  float   wob, wobV;                   // radius ringing: offset and its rate
  float   hue;                         // palette position, 0..256
  uint8_t live;
};

struct JbState {
  uint8_t  mode;
  uint8_t  clk[2];
  uint8_t  midEnv, trebEnv;
  float    t;
  JbBlob   b[JB_MAX];
};

static inline float jb_radius(const JbBlob &b) {
  // cube root of the volume, by two Newton steps from a good start - cbrtf
  // is not on every toolchain this builds with
  float r = 0.5f + 0.5f * b.vol;
  r = r - (r * r * r - b.vol) / (3.0f * r * r);
  r = r - (r * r * r - b.vol) / (3.0f * r * r);
  return r;
}

// Blend two palette positions round the circle, weighted.
static inline float jb_hueMix(float h1, float w1, float h2, float w2) {
  float d = h2 - h1;
  if (d > 128.0f) d -= 256.0f; else if (d < -128.0f) d += 256.0f;
  float h = h1 + d * (w2 / (w1 + w2));
  if (h < 0.0f) h += 256.0f; else if (h >= 256.0f) h -= 256.0f;
  return h;
}

static void jb_spawn(JbState *s, bool cube, float vol, float hue) {
  for (int k = 0; k < JB_MAX; k++) {
    JbBlob &b = s->b[k];
    if (b.live) continue;
    b.x = (float)hw_random16() * (1.2f / 65535.0f) - 0.6f;
    b.y = (float)hw_random16() * (1.2f / 65535.0f) - 0.6f;
    b.z = cube ? (float)hw_random16() * (1.2f / 65535.0f) - 0.6f : 0.0f;
    b.vx = (float)hw_random16() * (1.6f / 65535.0f) - 0.8f;
    b.vy = (float)hw_random16() * (1.6f / 65535.0f) - 0.8f;
    b.vz = cube ? (float)hw_random16() * (1.6f / 65535.0f) - 0.8f : 0.0f;
    b.vol = vol; b.wob = 0.0f; b.wobV = 0.0f; b.hue = hue; b.live = 1;
    return;
  }
}

static FX_RET mode_jelly_bounce() {
  if (!strip.isMatrix || !SEGMENT.is2D()) { SEGMENT.fill(SEGCOLOR(0)); FX_DONE; }
  const int cols = SEG_W, rows = SEG_H;
  if (cols < 8 || rows < 8) { SEGMENT.fill(SEGCOLOR(0)); FX_DONE; }

  const bool   cube = cfx_isCube(cols, rows);
  const int    B    = cube ? (cols / 3) : 1;
  const size_t m    = cfx_litCount(cols, rows, B, cube);

  const size_t need = sizeof(JbState) + 3 * m;
  if (!SEGENV.allocateData(need)) { SEGMENT.fill(SEGCOLOR(0)); FX_DONE; }
  JbState *s   = (JbState *)SEGENV.data;
  int8_t  *pos = (int8_t *)(s + 1);

  const uint8_t want = (uint8_t)(cube ? 1 : 2);
  if (SEGENV.call == 0 || s->mode != want) {
    memset(s, 0, sizeof(JbState));
    s->mode = want;
    for (int y = 0; y < rows; y++)
      for (int x = 0; x < cols; x++) {
        if (cube && cfx_gap(x, y, B)) continue;
        const size_t i = (size_t)cfx_cidx(x, y, cols, B, cube);
        float X, Y, Z; cfx_pos(x, y, cols, rows, B, cube, X, Y, Z);
        pos[i * 3] = cfx_clamp8(X); pos[i * 3 + 1] = cfx_clamp8(Y); pos[i * 3 + 2] = cfx_clamp8(Z);
      }
    for (int k = 0; k < 4; k++) jb_spawn(s, cube, 0.10f, (float)(k * 64));
  }

  uint16_t dt = fx_dt8(s->clk);
  if (dt > 50) dt = 50;
  const float dts = (float)dt * 0.001f;
  s->t += dts;

  // --- parameters ---------------------------------------------------------------------
  const float speedK = 0.4f + (float)SEGMENT.speed * (1.6f / 255.0f);        // how lively the box is
  const float sizeK  = 0.5f + (float)SEGMENT.intensity * (1.0f / 255.0f);    // jelly size
  const float pushK  = (float)SEGMENT.custom1 * (2.4f / 255.0f);              // outward push: hugging the glass
  const float mergeV = 0.2f + (float)SEGMENT.custom2 * (1.6f / 255.0f);      // the meeting speed that still merges
  const float wobK   = (float)cfx_c3full(SEGMENT.custom3) * (1.0f / 255.0f); // how much they ring
  const bool  glint  = SEGMENT.check2;

  // --- audio ------------------------------------------------------------------------
  um_data_t     *um   = cfx_getAudioData();
  const float    vol  = *(float *)um->u_data[0];
  const uint8_t *fft  = (const uint8_t *)um->u_data[2];
  const uint8_t  beat = SEGMENT.check1 ? fx_lowBeat(um) : 0;
  int bass, mid, treb; cfx_bands(fft, bass, mid, treb);
  s->midEnv  = fx_env(s->midEnv,  (uint8_t)mid,  dt, 300);
  s->trebEnv = fx_env(s->trebEnv, (uint8_t)treb, dt, 200);

  int live = 0;
  for (int k = 0; k < JB_MAX; k++) live += s->b[k].live;
  if (live < JB_MIN) jb_spawn(s, cube, 0.12f, (float)hw_random8());

  // --- the kick: split the biggest, shove everyone --------------------------------------
  if (beat) {
    const float force = 0.8f + (float)beat * (1.8f / 255.0f);
    int big = -1;
    for (int k = 0; k < JB_MAX; k++)
      if (s->b[k].live && (big < 0 || s->b[k].vol > s->b[big].vol)) big = k;
    int slot = -1;
    for (int k = 0; k < JB_MAX; k++) if (!s->b[k].live) { slot = k; break; }
    if (big >= 0 && slot >= 0 && s->b[big].vol > 0.03f) {
      JbBlob &p = s->b[big], &q = s->b[slot];
      float dx = (float)hw_random16() * (2.0f / 65535.0f) - 1.0f;
      float dy = (float)hw_random16() * (2.0f / 65535.0f) - 1.0f;
      float dz = cube ? (float)hw_random16() * (2.0f / 65535.0f) - 1.0f : 0.0f;
      float dl = sqrtf(dx * dx + dy * dy + dz * dz); if (dl < 1e-3f) { dx = 1; dl = 1; }
      dx /= dl; dy /= dl; dz /= dl;
      p.vol *= 0.5f;
      q = p;
      const float h0 = p.hue;
      p.hue = h0 + 85.0f; if (p.hue >= 256.0f) p.hue -= 256.0f;
      q.hue = h0 - 85.0f; if (q.hue < 0.0f)    q.hue += 256.0f;
      const float rr = jb_radius(p) * sizeK * 0.6f;
      p.x += dx * rr; p.y += dy * rr; p.z += dz * rr;
      q.x -= dx * rr; q.y -= dy * rr; q.z -= dz * rr;
      p.vx += dx * force; p.vy += dy * force; p.vz += dz * force;
      q.vx -= dx * force; q.vy -= dy * force; q.vz -= dz * force;
      p.wobV += 3.0f; q.wobV += 3.0f;
    }
    // the box is jolted: every jelly is thrown the same way at once. Random
    // shoves per jelly cancelled out and measured as barely an event.
    float jx = (float)hw_random16() * (2.0f / 65535.0f) - 1.0f;
    float jy = (float)hw_random16() * (2.0f / 65535.0f) - 1.0f;
    float jz = cube ? (float)hw_random16() * (2.0f / 65535.0f) - 1.0f : 0.0f;
    const float jl = sqrtf(jx * jx + jy * jy + jz * jz);
    if (jl > 1e-3f) { jx /= jl; jy /= jl; jz /= jl; } else jx = 1.0f;
    for (int k = 0; k < JB_MAX; k++) {
      JbBlob &b = s->b[k];
      if (!b.live) continue;
      b.vx += jx * force * 2.2f; b.vy += jy * force * 2.2f; b.vz += jz * force * 2.2f;
      b.wobV += 1.5f * force;
    }
  }

  // --- motion -----------------------------------------------------------------------------
  const float lim = 1.0f;                                    // the glass
  for (int k = 0; k < JB_MAX; k++) {
    JbBlob &b = s->b[k];
    if (!b.live) continue;
    const float r = jb_radius(b) * sizeK;
    // the outward push: they hug the glass
    const float L = sqrtf(b.x * b.x + b.y * b.y + b.z * b.z);
    if (L > 1e-3f) { const float a = pushK / L; b.vx += b.x * a * dts; b.vy += b.y * a * dts; b.vz += b.z * a * dts; }
    // keep off the open bottom: a bottomless cube shows nothing there
    if (cube && !cfx_sixFaces && b.z < -0.45f) b.vz += 1.6f * dts;
    // a little drag, so a shove settles rather than ringing for ever
    const float drag = 1.0f - 0.35f * dts;
    b.vx *= drag; b.vy *= drag; b.vz *= drag;
    b.x += b.vx * dts * speedK; b.y += b.vy * dts * speedK; b.z += b.vz * dts * speedK;
    // bounce: the centre may sink into the glass by half a radius - that is
    // the squash - and the jelly rings when it hits
    const float wall = lim - r * 0.5f;
    float *p[3] = { &b.x, &b.y, &b.z };
    float *v[3] = { &b.vx, &b.vy, &b.vz };
    for (int a = 0; a < (cube ? 3 : 2); a++) {
      if (*p[a] > wall)  { *p[a] = wall;  if (*v[a] > 0) { b.wobV -= *v[a] * 2.0f; *v[a] = -*v[a] * 0.75f; } }
      if (*p[a] < -wall) { *p[a] = -wall; if (*v[a] < 0) { b.wobV += *v[a] * 2.0f; *v[a] = -*v[a] * 0.75f; } }
    }
    if (!cube) b.z = 0.0f;
    // the ringing: a damped spring, kept going by the mids
    const float stiff = 60.0f, damp = 3.0f;
    b.wobV += (-stiff * b.wob - damp * b.wobV) * dts;
    b.wobV += ((float)hw_random8() - 127.5f) * ((float)s->midEnv * 0.0006f) * wobK;
    b.wob += b.wobV * dts;
    if (b.wob > 0.35f) b.wob = 0.35f; else if (b.wob < -0.35f) b.wob = -0.35f;
  }

  // --- meetings: merge the gentle ones, bounce the fast ones ------------------------------
  for (int i = 0; i < JB_MAX; i++) {
    JbBlob &a = s->b[i];
    if (!a.live) continue;
    for (int j = i + 1; j < JB_MAX; j++) {
      JbBlob &c = s->b[j];
      if (!c.live) continue;
      const float dx = c.x - a.x, dy = c.y - a.y, dz = c.z - a.z;
      const float d = sqrtf(dx * dx + dy * dy + dz * dz);
      const float ra = jb_radius(a) * sizeK, rc = jb_radius(c) * sizeK;
      if (d > (ra + rc) * 0.7f) continue;
      const float nx = d > 1e-4f ? dx / d : 1.0f, ny = d > 1e-4f ? dy / d : 0.0f, nz = d > 1e-4f ? dz / d : 0.0f;
      const float vn = (c.vx - a.vx) * nx + (c.vy - a.vy) * ny + (c.vz - a.vz) * nz;   // < 0: closing
      if (-vn < mergeV && d < (ra + rc) * 0.45f) {
        // merge into a: volumes add, momentum is kept, colours blend by volume
        const float tv = a.vol + c.vol;
        a.x = (a.x * a.vol + c.x * c.vol) / tv; a.y = (a.y * a.vol + c.y * c.vol) / tv; a.z = (a.z * a.vol + c.z * c.vol) / tv;
        a.vx = (a.vx * a.vol + c.vx * c.vol) / tv; a.vy = (a.vy * a.vol + c.vy * c.vol) / tv; a.vz = (a.vz * a.vol + c.vz * c.vol) / tv;
        a.hue = jb_hueMix(a.hue, a.vol, c.hue, c.vol);
        a.vol = tv > 0.5f ? 0.5f : tv;
        a.wobV += 2.5f;
        c.live = 0;
      } else if (vn < 0.0f) {
        // an elastic bounce along the line between them, weighted by volume
        const float ma = a.vol, mc = c.vol, imp = (2.0f * vn) / (ma + mc);
        a.vx += imp * mc * nx; a.vy += imp * mc * ny; a.vz += imp * mc * nz;
        c.vx -= imp * ma * nx; c.vy -= imp * ma * ny; c.vz -= imp * ma * nz;
        a.wobV += -vn; c.wobV += -vn;
      }
    }
  }

  // --- shade the glass --------------------------------------------------------------------
  // Per pixel: the summed field, and each jelly's share of it for the colour.
  const float glintK = glint ? (0.35f + 0.65f * (float)s->trebEnv * (1.0f / 255.0f)) : 0.0f;
  const uint8_t drive = cfx_drive(vol, 0.4f, 215);
  float rr2[JB_MAX];
  for (int k = 0; k < JB_MAX; k++) {
    const float r = s->b[k].live ? jb_radius(s->b[k]) * sizeK * (1.0f + s->b[k].wob) : 0.0f;
    rr2[k] = r * r;
  }
  CFX_NET_PREP();
  for (int y = 0; y < rows; y++) {
    CFX_NET_ROW(y);
    for (int x = 0; x < cols; x++) {
      CFX_NET_SKIP(x);
      const size_t i = (size_t)cfx_cidx(x, y, cols, B, cube);
      const float px = pos[i * 3] * (1.0f / 127.0f), py = pos[i * 3 + 1] * (1.0f / 127.0f), pz = pos[i * 3 + 2] * (1.0f / 127.0f);
      float F = 0.0f, hx = 0.0f, hy = 0.0f, best = 0.0f; int top = -1;
      float gx = 0.0f, gy = 0.0f, gz = 0.0f;               // the field's gradient: the jelly's surface normal
      for (int k = 0; k < JB_MAX; k++) {
        if (!rr2[k]) continue;
        const JbBlob &b = s->b[k];
        const float dx = px - b.x, dy = py - b.y, dz = pz - b.z;
        const float d2 = dx * dx + dy * dy + dz * dz + 1e-4f;
        const float f = rr2[k] / d2;
        if (f < 0.05f) continue;
        F += f;
        // the colour: palette positions blended round the circle by field share
        const float a = (b.hue) * (6.2831853f / 256.0f);
        hx += cfx_cosf16(a) * f; hy += cfx_sinf16(a) * f;
        if (f > best) { best = f; top = k; }
        const float gk = f / d2;
        gx += dx * gk; gy += dy * gk; gz += dz * gk;
      }
      uint32_t out = 0;
      if (F > 1.0f && top >= 0) {
        float hue = cfx_atan2f(hy, hx) * (256.0f / 6.2831853f);
        if (hue < 0.0f) hue += 256.0f;
        // rim bright just inside the surface, body translucent further in
        const float depth = 1.0f - 1.0f / F;                 // 0 at the surface, toward 1 deep inside
        float lum = depth < 0.18f ? 0.55f + 0.45f * (depth / 0.18f) : 1.0f - 0.55f * ((depth - 0.18f) / 0.82f);
        if (depth < 0.04f) lum *= depth / 0.04f;            // a soft edge, one pixel wide
        uint32_t c = SEGMENT.color_from_palette((uint8_t)hue, false, true, 0);
        c = mq_scale(c, (uint8_t)(lum * 255.0f));
        // the glint: where the jelly's surface faces a light up and to one side
        if (glintK > 0.0f) {
          const float gl = sqrtf(gx * gx + gy * gy + gz * gz);
          if (gl > 1e-5f) {
            float sp = (gx * 0.40f + gy * 0.35f + gz * 0.85f) / gl;
            if (sp > 0.80f) {
              sp = (sp - 0.80f) * 5.0f; sp *= sp;
              const int w = (int)(sp * glintK * 200.0f);
              int r = ((c >> 16) & 255) + w, g = ((c >> 8) & 255) + w, bl = (c & 255) + w;
              if (r > 255) r = 255; if (g > 255) g = 255; if (bl > 255) bl = 255;
              c = RGBW32(r, g, bl, 0);
            }
          }
        }
        out = c;
      }
      SEGMENT.setPixelColorXY(x, y, mq_scale(out, drive));
    }
  }
  FX_DONE;
}

static const char _data_FX_MODE_JELLY_BOUNCE[] PROGMEM =
  "Ace 3-D Jelly Bounce@Bounce,Jelly size,Cling,Merge,Wobble,Split on beat,Glint,Flat mode;;!;2f;sx=110,ix=120,c1=100,c2=110,c3=18,o1=1,o2=1,pal=11";
// AI: end


// ---------------------------------------------------------------------------
// Registration - joins the effect bank, which decides whether this effect
// claims one of the device's limited effect slots. See cube_fx_bank.h.
// ---------------------------------------------------------------------------
static CfxBankReg cube_fx_54_jelly_bounce_reg(&mode_jelly_bounce, _data_FX_MODE_JELLY_BOUNCE);
