#include "wled.h"
#include "cube_fx_common.h"
#include "cube_fx_bank.h"

// AI: below section was generated by an AI
// ===========================================================================
// Ace 3-D Murmuration - starlings round the cube, and a hawk on the kick
// ===========================================================================
// A flock, flown with Craig Reynolds' three steering rules ("Flocks, Herds,
// and Schools: A Distributed Behavioral Model", SIGGRAPH 1987,
// https://www.red3d.com/cwr/boids/): each bird steers AWAY from neighbours
// that crowd it, to MATCH the heading of the ones around it, and TOWARDS the
// middle of them. Nothing steers the flock as a whole, which is the point:
// the swirling, folding shape of a real murmuration is what those three local
// rules add up to, and it never repeats.
//
// The birds fly over a sphere and are drawn where their direction meets the
// cube (central projection), so the flock pours round edges and over the lid
// with no seam to cross. They keep off the ground: the cube has no bottom to
// draw them on, so a bird below the walls' midline climbs, as one would.
//
// Each bird leaves a fading trail - a long exposure of the flock, which at 16
// pixels a face is what lets the eye read its shape and flow rather than a
// scatter of dots. Black sky behind.
//
// Audio as force, not a meter:
//   kick      the flock WHEELS and the HAWK stoops. Every bird turns the
//             same way at once - about 70 degrees, paid off over ~140 ms - the
//             way a real murmuration banks in unison, so the whole picture
//             changes direction on the beat. And a hawk dives into the flock
//             from just outside it, so it strikes on the beat; every bird near
//             its line bolts away, faster than it can cruise, and the flock
//             folds back together by its own rules. The beat moves the flock;
//             it never touches the brightness. (The hawk alone measured as no
//             event in frame-to-frame change - a local scatter is swamped by a
//             flock that is always moving - which is why the wheel is here.)
//   bands     with Sub-flocks on, the birds are four flocks, one per band
//             (bass, low-mid, mid, treble) in four colours of the palette. A
//             flock flies faster the more energy its band carries, so the
//             flocks overtake and weave through each other with the music.
//             Birds cohere mostly with their own kind and avoid everyone, and
//             each flock follows its own roost - a point that wanders the
//             sphere on its own slow orbit - so the flocks keep apart as four
//             readable shapes and only weave through each other when their
//             roosts' paths cross.
//   treble    agitation: a jitter in every bird's steering - Chaos sets how
//             much - so a busy top end makes the whole flock restless.
// ===========================================================================

#define MU_MAXB     64
#define MU_FLOCKS   4

struct MuBird {
  float   x, y, z;                     // on the unit sphere (z = 0 on a panel)
  float   vx, vy, vz;                  // tangent velocity
  float   ox, oy, oz;                  // last frame's position, for the trail
  float   panic;                       // extra speed allowed after a fright, rad/s
  uint8_t flock;
};

struct MuHawk {
  float    x, y, z, vx, vy, vz;
  float    ox, oy, oz;
  uint16_t life;                       // ms left
};

struct MuState {
  uint8_t  mode;
  uint8_t  clk[2];
  uint8_t  nb;
  uint16_t drift;
  uint8_t  env[MU_FLOCKS];             // band envelopes, the flocks' push
  float    roostT;                      // the roosts' orbit clock, seconds
  float    wheel;                       // turn owed to the whole flock, radians (signed)
  MuHawk   hawk;
  MuBird   b[MU_MAXB];
};

// Put a point back where birds live: the unit sphere, or the panel's square.
static inline void mu_onto(bool cube, float &x, float &y, float &z) {
  if (cube) {
    const float L = sqrtf(x * x + y * y + z * z);
    if (L < 1e-5f) { z = 1.0f; return; }
    x /= L; y /= L; z /= L;
  } else {
    if (x < -1.0f) x = -1.0f; else if (x > 1.0f) x = 1.0f;
    if (y < -1.0f) y = -1.0f; else if (y > 1.0f) y = 1.0f;
    z = 0.0f;
  }
}

// Remove the component along the surface normal, so a velocity stays tangent.
static inline void mu_tangent(bool cube, float x, float y, float z, float &vx, float &vy, float &vz) {
  if (!cube) { vz = 0.0f; return; }
  const float d = vx * x + vy * y + vz * z;
  vx -= d * x; vy -= d * y; vz -= d * z;
}

// Compact index of the pixel a direction points at (cube), or a panel point.
static inline uint16_t mu_plot(bool cube, int cols, int rows, int B, const uint16_t *rev,
                               float x, float y, float z) {
  if (cube) {
    int f, a, b;
    cfx_face((int)(x * 300.0f), (int)(y * 300.0f), (int)(z * 300.0f), f, a, b);
    int ai = ((a + 128) * B) >> 8, bi = ((b + 128) * B) >> 8;
    if (ai < 0) ai = 0; else if (ai >= B) ai = B - 1;
    if (bi < 0) bi = 0; else if (bi >= B) bi = B - 1;
    return rev[((size_t)f * B + bi) * B + ai];
  }
  const int qx = (int)((x + 1.0f) * 0.5f * (float)cols), qy = (int)((1.0f - y) * 0.5f * (float)rows);
  if (qx < 0 || qy < 0 || qx >= cols || qy >= rows) return 0xFFFF;
  return (uint16_t)(qy * cols + qx);
}

// Brighten a pixel towards a colour (keep the brighter of each channel).
static inline void mu_stamp(uint8_t *g, uint16_t i, uint32_t c, uint8_t w) {
  if (i == 0xFFFF) return;
  uint8_t *p = g + (size_t)i * 3;
  const uint8_t r = scale8((uint8_t)(c >> 16), w), gg = scale8((uint8_t)(c >> 8), w), b = scale8((uint8_t)c, w);
  if (r  > p[0]) p[0] = r;
  if (gg > p[1]) p[1] = gg;
  if (b  > p[2]) p[2] = b;
}

// Draw the segment from the last position to this one, a pixel at a time.
static void mu_line(uint8_t *g, bool cube, int cols, int rows, int B, const uint16_t *rev,
                    float ax, float ay, float az, float bx, float by, float bz, uint32_t c, uint8_t w) {
  const float d = sqrtf((bx - ax) * (bx - ax) + (by - ay) * (by - ay) + (bz - az) * (bz - az));
  int sub = (int)(d * (float)(cube ? B : cols) * 0.6f) + 1;
  if (sub > 8) sub = 8;
  for (int k = 1; k <= sub; k++) {
    const float t = (float)k / (float)sub;
    float x = ax + (bx - ax) * t, y = ay + (by - ay) * t, z = az + (bz - az) * t;
    mu_onto(cube, x, y, z);
    mu_stamp(g, mu_plot(cube, cols, rows, B, rev, x, y, z), c, w);
  }
}

static void mu_seed(MuState *s, bool cube) {
  for (int i = 0; i < MU_MAXB; i++) {
    MuBird &b = s->b[i];
    // a loose cloud above the equator, so the flock forms in view
    b.x = (float)hw_random16() * (2.0f / 65535.0f) - 1.0f;
    b.y = (float)hw_random16() * (2.0f / 65535.0f) - 1.0f;
    b.z = cube ? 0.3f + (float)hw_random16() * (0.7f / 65535.0f) : 0.0f;
    mu_onto(cube, b.x, b.y, b.z);
    b.vx = (float)hw_random16() * (2.0f / 65535.0f) - 1.0f;
    b.vy = (float)hw_random16() * (2.0f / 65535.0f) - 1.0f;
    b.vz = cube ? (float)hw_random16() * (2.0f / 65535.0f) - 1.0f : 0.0f;
    mu_tangent(cube, b.x, b.y, b.z, b.vx, b.vy, b.vz);
    b.ox = b.x; b.oy = b.y; b.oz = b.z;
    b.flock = (uint8_t)(i % MU_FLOCKS);
  }
  s->hawk.life = 0;
}

static FX_RET mode_murmuration() {
  if (!strip.isMatrix || !SEGMENT.is2D()) { SEGMENT.fill(SEGCOLOR(0)); FX_DONE; }
  const int cols = SEG_W, rows = SEG_H;
  if (cols < 8 || rows < 8) { SEGMENT.fill(SEGCOLOR(0)); FX_DONE; }

  const bool   cube = cfx_isCube(cols, rows);
  const int    B    = cube ? (cols / 3) : 1;
  const size_t m    = cfx_litCount(cols, rows, B, cube);
  const size_t lut  = cube ? (size_t)6 * B * B : 0;

  const size_t need = sizeof(MuState) + 3 * m + lut * sizeof(uint16_t) + 2;
  if (!SEGENV.allocateData(need)) { SEGMENT.fill(SEGCOLOR(0)); FX_DONE; }
  MuState  *s   = (MuState *)SEGENV.data;
  uint8_t  *g   = (uint8_t *)(s + 1);
  uint16_t *rev = (uint16_t *)(((uintptr_t)(g + 3 * m) + 1) & ~(uintptr_t)1);

  const uint8_t want = (uint8_t)(cube ? 1 : 2);
  if (SEGENV.call == 0 || s->mode != want) {
    memset(s, 0, sizeof(MuState));
    s->mode = want;
    memset(g, 0, 3 * m);
    if (cube) cfx_buildRev(rev, cols, rows, B);
    mu_seed(s, cube);
  }

  uint16_t dt = fx_dt8(s->clk);
  if (dt > 50) dt = 50;
  const float dts = (float)dt * 0.001f;

  // --- parameters -----------------------------------------------------------------
  const float vBase  = 0.35f + (float)SEGMENT.speed * (1.25f / 255.0f);      // cruising speed, rad/s
  const float tight  = 0.4f + (float)SEGMENT.intensity * (1.6f / 255.0f);    // cohesion + alignment
  int nb = 16 + ((int)SEGMENT.custom1 * (MU_MAXB - 16)) / 255;                 // birds
  const int   trailI = (int)SEGMENT.custom2;                                   // trail length
  const float chaos  = (float)cfx_c3full(SEGMENT.custom3) * (1.0f / 255.0f);
  const bool  flocks = SEGMENT.check2;
  if (nb > MU_MAXB) nb = MU_MAXB;
  s->nb = (uint8_t)nb;

  // --- audio --------------------------------------------------------------------
  um_data_t     *um   = cfx_getAudioData();
  const float    vol  = *(float *)um->u_data[0];
  const uint8_t *fft  = (const uint8_t *)um->u_data[2];
  const uint8_t  beat = SEGMENT.check1 ? fx_lowBeat(um) : 0;
  {
    const int band[MU_FLOCKS] = { (fft[0] + fft[1] + fft[2]) / 3, (fft[3] + fft[4] + fft[5]) / 3,
                                  (fft[6] + fft[7] + fft[8] + fft[9]) / 4,
                                  (fft[11] + fft[12] + fft[13] + fft[14] + fft[15]) / 5 };
    for (int f = 0; f < MU_FLOCKS; f++) s->env[f] = fx_env(s->env[f], (uint8_t)band[f], dt, 400);
  }
  const float treb = (float)s->env[3] * (1.0f / 255.0f);

  s->drift = (uint16_t)(s->drift + dt * 2);
  const uint8_t hueBase = (uint8_t)(s->drift >> 8);

  // The hawk: it stoops from just outside the flock, through its middle, so
  // it strikes on the beat rather than a long flight after it.
  if (beat && !s->hawk.life) {
    // the middle of a randomly picked bird's neighbourhood
    const MuBird &t = s->b[hw_random8() % nb];
    float cx = 0, cy = 0, cz = 0; int cn = 0;
    for (int j = 0; j < nb; j++) {
      const float dx = s->b[j].x - t.x, dy = s->b[j].y - t.y, dz = s->b[j].z - t.z;
      if (dx * dx + dy * dy + dz * dz < 0.25f) { cx += s->b[j].x; cy += s->b[j].y; cz += s->b[j].z; cn++; }
    }
    cx /= cn; cy /= cn; cz /= cn;
    mu_onto(cube, cx, cy, cz);
    // a random heading through that point
    float hx = (float)hw_random16() * (2.0f / 65535.0f) - 1.0f;
    float hy = (float)hw_random16() * (2.0f / 65535.0f) - 1.0f;
    float hz = cube ? (float)hw_random16() * (2.0f / 65535.0f) - 1.0f : 0.0f;
    mu_tangent(cube, cx, cy, cz, hx, hy, hz);
    float hl = sqrtf(hx * hx + hy * hy + hz * hz); if (hl < 1e-4f) { hx = 1; hl = 1; }
    hx /= hl; hy /= hl; hz /= hl;
    const float sp = 2.6f + (float)beat * (1.6f / 255.0f);
    MuHawk &h = s->hawk;
    h.x = cx - hx * 0.30f; h.y = cy - hy * 0.30f; h.z = cz - hz * 0.30f;
    mu_onto(cube, h.x, h.y, h.z);
    h.vx = hx * sp; h.vy = hy * sp; h.vz = hz * sp;
    h.ox = h.x; h.oy = h.y; h.oz = h.z;
    h.life = 520;
  }

  // The wheel: a turn owed, added on the kick and paid off a third a frame.
  if (beat) {
    float w = s->wheel + ((hw_random8() & 1) ? 1.0f : -1.0f) * (0.9f + (float)beat * (0.5f / 255.0f));
    if (w > 2.5f) w = 2.5f; else if (w < -2.5f) w = -2.5f;
    s->wheel = w;
  }
  float turn = 0.0f;
  if (s->wheel != 0.0f) {
    turn = s->wheel * ((float)dt / 70.0f);
    if (fabsf(turn) > fabsf(s->wheel) || fabsf(s->wheel) < 0.01f) turn = s->wheel;
    s->wheel -= turn;
  }
  const float tc = cosf(turn), ts = sinf(turn);

  // --- flight ---------------------------------------------------------------------
  s->roostT += dts * (0.5f + vBase);
  const float rN2 = 0.42f * 0.42f;        // neighbourhood
  const float rS2 = 0.20f * 0.20f;        // too close: a couple of pixels
  MuHawk &h = s->hawk;
  for (int i = 0; i < nb; i++) {
    MuBird &b = s->b[i];
    if (turn != 0.0f) {
      // rotate the heading about the surface normal: v cos + (n x v) sin
      float nx = 0.0f, ny = 0.0f, nz = 1.0f;
      if (cube) { nx = b.x; ny = b.y; nz = b.z; }
      const float cx = ny * b.vz - nz * b.vy, cy = nz * b.vx - nx * b.vz, cz = nx * b.vy - ny * b.vx;
      b.vx = b.vx * tc + cx * ts; b.vy = b.vy * tc + cy * ts; b.vz = b.vz * tc + cz * ts;
    }
    float sx = 0, sy = 0, sz = 0;         // separation
    float ax = 0, ay = 0, az = 0;         // alignment
    float cx = 0, cy = 0, cz = 0, cw = 0; // cohesion
    for (int j = 0; j < nb; j++) {
      if (j == i) continue;
      const MuBird &o = s->b[j];
      const float dx = b.x - o.x, dy = b.y - o.y, dz = b.z - o.z;
      const float d2 = dx * dx + dy * dy + dz * dz;
      if (d2 > rN2) continue;
      if (d2 < rS2) { const float k = 1.0f / (d2 + 0.002f); sx += dx * k; sy += dy * k; sz += dz * k; }
      // birds follow their own flock closely and the others loosely
      const float w = (!flocks || o.flock == b.flock) ? 1.0f : 0.08f;
      ax += o.vx * w; ay += o.vy * w; az += o.vz * w;
      cx += o.x * w;  cy += o.y * w;  cz += o.z * w; cw += w;
    }
    float fx = sx * 0.07f, fy = sy * 0.07f, fz = sz * 0.07f;
    if (cw > 0.0f) {
      const float ic = 1.0f / cw;
      // alignment strong and cohesion gentle: a stream that folds, not a ball
      fx += (ax * ic - b.vx) * 1.6f * tight + (cx * ic - b.x) * 0.9f * tight;
      fy += (ay * ic - b.vy) * 1.6f * tight + (cy * ic - b.y) * 0.9f * tight;
      fz += (az * ic - b.vz) * 1.6f * tight + (cz * ic - b.z) * 0.9f * tight;
    }
    // the roost: a gentle pull towards this flock's wandering home
    {
      const float t = s->roostT * (0.11f + 0.04f * (float)b.flock) + (float)b.flock * 1.7f;
      float rx = cfx_cosf16(t) * cfx_cosf16(t * 0.61f + b.flock), ry = cfx_sinf16(t) * cfx_cosf16(t * 0.61f + b.flock);
      float rz = cube ? 0.15f + 0.55f * cfx_sinf16(t * 0.61f + b.flock) : 0.0f;
      if (!flocks) { rx = cfx_cosf16(s->roostT * 0.13f); ry = cfx_sinf16(s->roostT * 0.13f); rz = cube ? 0.4f : 0.0f; }
      if (!cube) { rx *= 0.6f; ry *= 0.6f; }
      mu_onto(cube, rx, ry, rz);
      fx += (rx - b.x) * 0.9f; fy += (ry - b.y) * 0.9f; fz += (rz - b.z) * 0.9f;
    }
    // restlessness: a random steer, more with Chaos and more with treble
    const float jit = (0.6f + 6.0f * chaos * (0.25f + treb));
    fx += ((float)hw_random8() - 127.5f) * (jit / 127.5f);
    fy += ((float)hw_random8() - 127.5f) * (jit / 127.5f);
    if (cube) fz += ((float)hw_random8() - 127.5f) * (jit / 127.5f);
    // keep off the ground the cube has no face for, and away from a panel's rim
    if (cube && !cfx_sixFaces && b.z < -0.35f) fz += (-0.35f - b.z) * 14.0f;
    if (!cube) {
      if (b.x >  0.8f) fx -= (b.x - 0.8f) * 30.0f; else if (b.x < -0.8f) fx -= (b.x + 0.8f) * 30.0f;
      if (b.y >  0.8f) fy -= (b.y - 0.8f) * 30.0f; else if (b.y < -0.8f) fy -= (b.y + 0.8f) * 30.0f;
    }
    // the hawk: bolt straight away from it
    if (h.life) {
      const float dx = b.x - h.x, dy = b.y - h.y, dz = b.z - h.z;
      const float d2 = dx * dx + dy * dy + dz * dz;
      if (d2 < 0.50f) {
        const float k = 90.0f / (d2 + 0.02f); fx += dx * k; fy += dy * k; fz += dz * k;
        // a fright lifts the bird's top speed - without this the scatter was
        // capped at cruising speed and measured as no event at all
        const float p = 5.0f * (1.0f - d2 / 0.50f);
        if (p > b.panic) b.panic = p;
      }
    }
    b.vx += fx * dts; b.vy += fy * dts; b.vz += fz * dts;
    mu_tangent(cube, b.x, b.y, b.z, b.vx, b.vy, b.vz);
    // speed: cruising, plus the push of this flock's band, within limits
    const float push = flocks ? (float)s->env[b.flock] * (1.0f / 255.0f) : (float)vol * (1.0f / 255.0f);
    const float vMin = vBase * (0.6f + 0.6f * push), vMax = vBase * (1.6f + 1.2f * push) + 1.5f + b.panic;
    b.panic *= 1.0f - 2.5f * dts;                      // the fright wears off in about 400 ms
    float sp = sqrtf(b.vx * b.vx + b.vy * b.vy + b.vz * b.vz);
    if (sp < 1e-4f) { b.vx = vMin; sp = vMin; }
    const float tgt = sp < vMin ? vMin : (sp > vMax ? vMax : sp);
    const float k = tgt / sp;
    b.vx *= k; b.vy *= k; b.vz *= k;
    b.ox = b.x; b.oy = b.y; b.oz = b.z;
    b.x += b.vx * dts; b.y += b.vy * dts; b.z += b.vz * dts;
    mu_onto(cube, b.x, b.y, b.z);
    mu_tangent(cube, b.x, b.y, b.z, b.vx, b.vy, b.vz);
  }
  if (h.life) {
    h.ox = h.x; h.oy = h.y; h.oz = h.z;
    h.x += h.vx * dts; h.y += h.vy * dts; h.z += h.vz * dts;
    mu_onto(cube, h.x, h.y, h.z);
    mu_tangent(cube, h.x, h.y, h.z, h.vx, h.vy, h.vz);
    h.life = (h.life > dt) ? (uint16_t)(h.life - dt) : 0;
  }

  // --- draw ---------------------------------------------------------------------------
  // The trail: the glow decays every frame - 0.80 per 23 ms at no Trails, 0.97 at full.
  {
    const int keep23 = 204 + (trailI * 44) / 255;
    const uint8_t keep = (uint8_t)(255 - fx_fade(255 - keep23, dt));
    for (size_t i = 0; i < 3 * m; i++) g[i] = scale8(g[i], keep);
  }
  for (int i = 0; i < nb; i++) {
    const MuBird &b = s->b[i];
    uint8_t hue;
    if (flocks) hue = (uint8_t)(hueBase + b.flock * 64);
    else {
      // one flock, each bird coloured by the way it is heading
      const float a = cube ? cfx_atan2f(b.vy, b.vx + b.vz * 0.5f) : cfx_atan2f(b.vy, b.vx);
      hue = (uint8_t)(hueBase + (int)(a * (128.0f / 3.14159265f)));
    }
    const uint32_t c = SEGMENT.color_from_palette(hue, false, true, 0);
    mu_line(g, cube, cols, rows, B, rev, b.ox, b.oy, b.oz, b.x, b.y, b.z, c, 255);
    // a soft halo round the head: the four pixels beside it, dimmer
    {
      float sp = sqrtf(b.vx * b.vx + b.vy * b.vy + b.vz * b.vz); if (sp < 1e-4f) sp = 1.0f;
      const float t1x = b.vx / sp, t1y = b.vy / sp, t1z = b.vz / sp;
      float t2x, t2y, t2z;
      if (cube) { t2x = b.y * t1z - b.z * t1y; t2y = b.z * t1x - b.x * t1z; t2z = b.x * t1y - b.y * t1x; }
      else      { t2x = -t1y; t2y = t1x; t2z = 0.0f; }
      const float px = cube ? 1.5707963f / (float)B : 2.0f / (float)cols;
      for (int q = 0; q < 4; q++) {
        const float sa = (q & 1) ? -px : px;
        float x = b.x + ((q < 2) ? t1x : t2x) * sa, y = b.y + ((q < 2) ? t1y : t2y) * sa, z = b.z + ((q < 2) ? t1z : t2z) * sa;
        mu_onto(cube, x, y, z);
        mu_stamp(g, mu_plot(cube, cols, rows, B, rev, x, y, z), c, 90);
      }
    }
  }
  if (h.life) {
    // the hawk: white, hard, a pixel wider than the birds
    const uint8_t w = (uint8_t)(h.life > 160 ? 255 : (h.life * 255) / 160);
    mu_line(g, cube, cols, rows, B, rev, h.ox, h.oy, h.oz, h.x, h.y, h.z, RGBW32(255, 255, 255, 0), w);
  }

  // --- present ------------------------------------------------------------------------------
  const uint8_t drive = cfx_drive(vol, 0.4f, 215);
  CFX_NET_PREP();
  for (int y = 0; y < rows; y++) {
    CFX_NET_ROW(y);
    for (int x = 0; x < cols; x++) {
      CFX_NET_SKIP(x);
      const size_t i = (size_t)cfx_cidx(x, y, cols, B, cube);
      SEGMENT.setPixelColorXY(x, y, mq_scale(RGBW32(g[i * 3], g[i * 3 + 1], g[i * 3 + 2], 0), drive));
    }
  }
  FX_DONE;
}

static const char _data_FX_MODE_MURMURATION[] PROGMEM =
  "Ace 3-D Murmuration@Flight speed,Tightness,Birds,Trails,Chaos,Hawk on beat,Sub-flocks,Flat mode;;!;2f;sx=130,ix=120,c1=210,c2=110,c3=10,o1=1,o2=1,pal=11";
// AI: end


// ---------------------------------------------------------------------------
// Registration - joins the effect bank, which decides whether this effect
// claims one of the device's limited effect slots. See cube_fx_bank.h.
// ---------------------------------------------------------------------------
static CfxBankReg cube_fx_53_murmuration_reg(&mode_murmuration, _data_FX_MODE_MURMURATION);
