#include "wled.h"
#include "cube_fx_common.h"
#include "cube_fx_bank.h"

// AI: below section was generated by an AI
// ===========================================================================
// Ace 3-D Paintball - the cube as a target, the music as the gun
// ===========================================================================
// Paint balls hit the solid from every direction. Each one lands as a SPLAT:
// a star of a core and spikes, flung droplets beyond it, and a glossy wet
// sheen that dries off in a moment. The paint stays where it landed, layered
// over the paint beneath, and slowly fades back to the black of the target.
// Then gravity takes what is still wet: drips run DOWN the walls, wander a
// little as real runs do, thin out as their paint is used up and end in a
// small bead - or run clean off the bottom edge. On the lid there is no
// "down", so paint there creeps outwards to the nearest edge and spills over
// it, which is what a lid that is very slightly domed would do.
//
// Audio is placement and force, not a meter:
//   kick      a VOLLEY. One ball, two on a hard hit, three on a very hard one,
//             sized by how hard it hit. The splat spreads over ~140 ms rather
//             than appearing - the beat moves paint, it does not flash a gain.
//   the mix   between beats balls keep coming at Fire rate, faster the more
//             there is in the mix, each announced by a shrinking aim ring a
//             fifth of a second before it lands.
//   colour    which band fired it. Kicks shoot the bass end of the palette;
//             the others pick a band by its energy, so a bright hi-hat section
//             paints in the treble end's colours.
//   treble    spray - fine speckle around the newest splat, as a high-pressure
//             gun leaves.
//
// Every position is a 3-D point on the surface, so splats wrap over edges
// and drips turn the corner from the lid onto a wall with no seam handling:
// a moved point is pushed back onto the surface by central projection (divide
// by its largest coordinate), and the shape test unfolds the chord to a
// neighbouring face so a splat straddling an edge keeps its spikes.
// ===========================================================================

#define PB_MAXDRIP  28
#define PB_MAXBALL  8
#define PB_LOBES    6
#define PB_SPLATMS  160                 // how long a splat takes to spread
#define PB_AIMMS    200                 // the aim ring before an un-beat shot lands
#define PB_SHEENMS  260                 // the wet gloss, gone in about this

struct PbDrip {
  float   x, y, z;                      // on the surface
  float   paint;                        // 1 at birth, the run ends at 0
  float   wob;                          // its own wobble phase
  uint8_t hue;
  uint8_t live;
};

struct PbBall {
  float    x, y, z;                     // landing point, on the surface
  float    R;                           // full splat radius (chord units)
  float    lx[PB_LOBES], ly[PB_LOBES];  // spike directions in the tangent plane
  float    ll[PB_LOBES];                // spike lengths
  float    rough;                       // phase of the rim's irregularity
  uint16_t age;                         // ms since it became a ball
  uint16_t aim;                         // ms of aim ring before it lands
  uint8_t  hue;
  uint8_t  live;
};

struct PbState {
  uint8_t  mode;
  uint8_t  clk[2];
  uint8_t  lastBall;                    // the newest splat: the spray's centre
  uint16_t drift;                       // slow palette drift
  float    fireDebt;                    // auto-fire accumulator, in balls
  uint16_t dryDebt;                     // linear drying owed, Q8 levels
  float    wobT;
  PbDrip   drip[PB_MAXDRIP];
  PbBall   ball[PB_MAXBALL];
};

// --- surface helpers ---------------------------------------------------------
// Push a point back onto the surface: the cube by central projection (divide
// by the largest coordinate), the panel by clamping into the square.
static inline void pb_onto(bool cube, float &x, float &y, float &z) {
  if (cube) {
    const float ax = fabsf(x), ay = fabsf(y), az = fabsf(z);
    float mx = ax > ay ? ax : ay; if (az > mx) mx = az;
    if (mx < 1e-4f) { z = 1.0f; return; }
    const float k = 1.0f / mx;
    x *= k; y *= k; z *= k;
  } else {
    if (x < -1.0f) x = -1.0f; else if (x > 1.0f) x = 1.0f;
    if (y < -1.0f) y = -1.0f; else if (y > 1.0f) y = 1.0f;
    z = 0.0f;
  }
}

// The outward normal at a surface point (its dominant axis) and two tangent
// directions completing a basis there. The panel is the plane z = 0.
static inline void pb_frame(bool cube, float x, float y, float z,
                            float n[3], float t1[3], float t2[3]) {
  n[0] = n[1] = n[2] = 0; t1[0] = t1[1] = t1[2] = 0; t2[0] = t2[1] = t2[2] = 0;
  if (!cube) { n[2] = 1; t1[0] = 1; t2[1] = 1; return; }
  const float ax = fabsf(x), ay = fabsf(y), az = fabsf(z);
  if (az >= ax && az >= ay) { n[2] = z >= 0 ? 1.0f : -1.0f; t1[0] = 1; t2[1] = 1; }
  else if (ay >= ax)        { n[1] = y >= 0 ? 1.0f : -1.0f; t1[0] = 1; t2[2] = 1; }
  else                      { n[0] = x >= 0 ? 1.0f : -1.0f; t1[1] = 1; t2[2] = 1; }
}

// Compact pixel index of a surface point, 0xFFFF when nothing is lit there.
static inline uint16_t pb_plot(bool cube, int cols, int rows, int B, const uint16_t *rev,
                               float x, float y, float z) {
  if (cube) {
    int f, a, b;
    cfx_face((int)(x * 300.0f), (int)(y * 300.0f), (int)(z * 300.0f), f, a, b);
    int ai = ((a + 128) * B) >> 8, bi = ((b + 128) * B) >> 8;
    if (ai < 0) ai = 0; else if (ai >= B) ai = B - 1;
    if (bi < 0) bi = 0; else if (bi >= B) bi = B - 1;
    return rev[((size_t)f * B + bi) * B + ai];
  }
  const int qx = (int)((x + 1.0f) * 0.5f * (float)cols), qy = (int)((1.0f - y) * 0.5f * (float)rows);
  if (qx < 0 || qy < 0 || qx >= cols || qy >= rows) return 0xFFFF;
  return (uint16_t)(qy * cols + qx);
}

// Paint one pixel: new paint covers the old, it does not mix with it.
static inline void pb_put(uint8_t *paint, uint8_t *wet, uint16_t i, uint32_t c, uint8_t w) {
  if (i == 0xFFFF) return;
  uint8_t *p = paint + (size_t)i * 3;
  p[0] = (uint8_t)(c >> 16); p[1] = (uint8_t)(c >> 8); p[2] = (uint8_t)c;
  if (w > wet[i]) wet[i] = w;
}

// A random landing point, uniform over the lit faces: a random direction,
// centrally projected, rejected from the bottom unless the cube has one.
static void pb_target(bool cube, float &x, float &y, float &z) {
  for (int tries = 0; tries < 8; tries++) {
    x = (float)hw_random16() * (2.0f / 65535.0f) - 1.0f;
    y = (float)hw_random16() * (2.0f / 65535.0f) - 1.0f;
    z = (float)hw_random16() * (2.0f / 65535.0f) - 1.0f;
    if (!cube) { z = 0.0f; return; }
    pb_onto(true, x, y, z);
    if (z > -0.999f || cfx_sixFaces) return;
  }
  z = 1.0f;
}

// Unfolded tangent-plane coordinates of q relative to the splat centre p:
// the chord's normal part is folded back into the tangent direction, so a
// pixel round an edge sits as far out as the surface path to it, not the
// straight line through the solid.
static inline void pb_unfold(const float d[3], const float n[3], const float t1[3], const float t2[3],
                             float &u, float &v) {
  const float dn = d[0] * n[0] + d[1] * n[1] + d[2] * n[2];
  u = d[0] * t1[0] + d[1] * t1[1] + d[2] * t1[2];
  v = d[0] * t2[0] + d[1] * t2[1] + d[2] * t2[2];
  const float L = sqrtf(u * u + v * v);
  if (L > 1e-5f && dn != 0.0f) { const float k = (L + fabsf(dn)) / L; u *= k; v *= k; }
}

// How far the splat's rim reaches in direction (cu, cv) (a unit vector), as a
// fraction of R: a ragged core plus the spikes, each a cosine raised to the
// 16th power so it is narrow.
static inline float pb_rim(const PbBall &b, float cu, float cv) {
  float r = 0.55f + 0.07f * sinf(3.0f * atan2f(cv, cu) + b.rough);
  for (int k = 0; k < PB_LOBES; k++) {
    float c = cu * b.lx[k] + cv * b.ly[k];
    if (c <= 0.0f) continue;
    c *= c; c *= c; c *= c; c *= c;            // ^16
    const float s = 0.55f + b.ll[k] * c;
    if (s > r) r = s;
  }
  return r;
}

static void pb_fire(PbState *s, bool cube, float R, uint8_t hue, uint16_t aim) {
  int slot = -1;
  for (int k = 0; k < PB_MAXBALL; k++) if (!s->ball[k].live) { slot = k; break; }
  if (slot < 0) return;
  PbBall &b = s->ball[slot];
  pb_target(cube, b.x, b.y, b.z);
  b.R = R; b.hue = hue; b.age = 0; b.aim = aim; b.live = 1;
  b.rough = (float)hw_random8() * (6.2831853f / 255.0f);
  for (int k = 0; k < PB_LOBES; k++) {
    const float a = (float)hw_random16() * (6.2831853f / 65535.0f);
    b.lx[k] = cosf(a); b.ly[k] = sinf(a);
    b.ll[k] = 0.35f + (float)hw_random8() * (0.75f / 255.0f);
  }
}

static FX_RET mode_paintball() {
  if (!strip.isMatrix || !SEGMENT.is2D()) { SEGMENT.fill(SEGCOLOR(0)); FX_DONE; }
  const int cols = SEG_W, rows = SEG_H;
  if (cols < 8 || rows < 8) { SEGMENT.fill(SEGCOLOR(0)); FX_DONE; }

  const bool   cube = cfx_isCube(cols, rows);
  const int    B    = cube ? (cols / 3) : 1;
  const size_t m    = cfx_litCount(cols, rows, B, cube);
  const size_t lut  = cube ? (size_t)6 * B * B : 0;

  // paint RGB, wet gloss, the pixel's own position (int8 x3), the rev table
  const size_t need = sizeof(PbState) + 3 * m + m + 3 * m + lut * sizeof(uint16_t) + 2;
  if (!SEGENV.allocateData(need)) { SEGMENT.fill(SEGCOLOR(0)); FX_DONE; }
  PbState  *s     = (PbState *)SEGENV.data;
  uint8_t  *paint = (uint8_t *)(s + 1);
  uint8_t  *wet   = paint + 3 * m;
  int8_t   *pos   = (int8_t *)(wet + m);
  uint16_t *rev   = (uint16_t *)(((uintptr_t)(pos + 3 * m) + 1) & ~(uintptr_t)1);

  const uint8_t want = (uint8_t)(cube ? 1 : 2);
  if (SEGENV.call == 0 || s->mode != want) {
    memset(s, 0, sizeof(PbState));
    s->mode = want;
    memset(paint, 0, 3 * m); memset(wet, 0, m);
    for (int y = 0; y < rows; y++)
      for (int x = 0; x < cols; x++) {
        if (cube && cfx_gap(x, y, B)) continue;
        const size_t i = (size_t)cfx_cidx(x, y, cols, B, cube);
        float X, Y, Z; cfx_pos(x, y, cols, rows, B, cube, X, Y, Z);
        pos[i * 3] = cfx_clamp8(X); pos[i * 3 + 1] = cfx_clamp8(Y); pos[i * 3 + 2] = cfx_clamp8(Z);
      }
    if (cube) cfx_buildRev(rev, cols, rows, B);
  }

  uint16_t dt = fx_dt8(s->clk);
  if (dt > 60) dt = 60;
  const float dts = (float)dt * 0.001f;

  // --- parameters ---------------------------------------------------------------
  const float runSpeed = 0.15f + (float)SEGMENT.speed * (1.1f / 255.0f);      // drip speed, chord units/s
  const float sizeK    = 0.16f + (float)SEGMENT.intensity * (0.34f / 255.0f); // splat radius
  const float fireRate = (float)SEGMENT.custom1 * (3.0f / 255.0f);            // auto shots a second, at full mix
  const int   drips    = (int)SEGMENT.custom2;                                 // how much runs
  const int   dryI     = (int)cfx_c3full(SEGMENT.custom3);                    // how long paint stays
  const bool  sheenOn  = SEGMENT.check2;

  // --- audio ----------------------------------------------------------------------
  um_data_t     *um   = cfx_getAudioData();
  const float    vol  = *(float *)um->u_data[0];
  const uint8_t *fft  = (const uint8_t *)um->u_data[2];
  const uint8_t  beat = SEGMENT.check1 ? fx_lowBeat(um) : 0;
  int bass, mid, treb; cfx_bands(fft, bass, mid, treb);
  const int lowMid = (fft[3] + fft[4]) / 2;
  const float mix = (float)(bass + lowMid + mid + treb) * (1.0f / 1020.0f);

  s->drift = (uint16_t)(s->drift + dt * 3);
  const uint8_t hueBase = (uint8_t)(s->drift >> 8);

  // A kick is a volley: one ball, more on a harder hit, sized by the hit.
  if (beat) {
    const int nb = 1 + (beat > 170) + (beat > 225);
    const float R = sizeK * (0.75f + (float)beat * (0.55f / 255.0f));
    for (int k = 0; k < nb; k++)
      pb_fire(s, cube, R * (k ? 0.7f : 1.0f), (uint8_t)(hueBase + k * 85 + hw_random8() % 40), 0);   // a volley is several colours
  }
  // Between beats: shots at Fire rate, quicker the fuller the mix, each with
  // a band picked by its share of the energy - that band is its colour.
  s->fireDebt += fireRate * (0.25f + 0.75f * mix) * dts;
  if (s->fireDebt > 2.0f) s->fireDebt = 2.0f;
  while (s->fireDebt >= 1.0f) {
    s->fireDebt -= 1.0f;
    const int e[4] = { bass + 8, lowMid + 8, mid + 8, treb + 8 };
    int pick = (int)hw_random16() % (e[0] + e[1] + e[2] + e[3]), band = 0;
    while (band < 3 && pick >= e[band]) { pick -= e[band]; band++; }
    const float R = sizeK * (0.55f + (float)hw_random8() * (0.4f / 255.0f));
    pb_fire(s, cube, R, (uint8_t)(hueBase + band * 64 + hw_random8() % 36), PB_AIMMS);
  }

  // --- dry the paint ----------------------------------------------------------------
  // LINEAR, not multiplicative: paint stays vivid and then dries away over a
  // set lifetime - 1.2 s at no Dry time to 12 s at full. A multiplicative fade
  // spends most of a splat's life as a dim smear, which is the opposite of
  // paint. The brightest channel loses the step and the others follow it in
  // proportion, so a colour keeps its hue as it goes.
  {
    const uint32_t lifeMs = 1200u + (uint32_t)dryI * 10800u / 255u;
    s->dryDebt = (uint16_t)(s->dryDebt + (uint32_t)dt * 255u * 256u / lifeMs);
    const int k = s->dryDebt >> 8;
    s->dryDebt &= 0xFF;
    if (k) for (size_t i = 0; i < m; i++) {
      uint8_t *p = paint + i * 3;
      const int mx = p[0] > p[1] ? (p[0] > p[2] ? p[0] : p[2]) : (p[1] > p[2] ? p[1] : p[2]);
      if (!mx) continue;
      const int nm = mx - k;
      if (nm <= 0) { p[0] = p[1] = p[2] = 0; continue; }
      p[0] = (uint8_t)((p[0] * nm) / mx); p[1] = (uint8_t)((p[1] * nm) / mx); p[2] = (uint8_t)((p[2] * nm) / mx);
    }
    const uint8_t wf = fx_fade((23 * 255) / PB_SHEENMS, dt);
    for (size_t i = 0; i < m; i++) wet[i] = (wet[i] > wf) ? (uint8_t)(wet[i] - wf) : 0;
  }

  // --- balls: aim, land, spread, then spawn the drips ------------------------------------
  for (int k = 0; k < PB_MAXBALL; k++) {
    PbBall &b = s->ball[k];
    if (!b.live) continue;
    b.age = (uint16_t)(b.age + dt);
    if (b.age < b.aim) continue;                       // still in the air
    const uint16_t sa = (uint16_t)(b.age - b.aim);

    float n[3], t1[3], t2[3];
    pb_frame(cube, b.x, b.y, b.z, n, t1, t2);
    // spreading: from a dot to all of it, easing out - measured, a splat that
    // started at a third of its size put the whole hit into one frame
    float a = (float)(sa + dt) / (float)PB_SPLATMS; if (a > 1.0f) a = 1.0f;
    const float grow = 0.08f + 0.92f * (1.0f - (1.0f - a) * (1.0f - a));
    const float Rn = b.R * grow, reach = Rn * 1.65f;

    for (size_t i = 0; i < m; i++) {
      const float d[3] = { pos[i * 3] * (1.0f / 127.0f) - b.x, pos[i * 3 + 1] * (1.0f / 127.0f) - b.y,
                           pos[i * 3 + 2] * (1.0f / 127.0f) - b.z };
      if (fabsf(d[0]) > reach || fabsf(d[1]) > reach || fabsf(d[2]) > reach) continue;
      float u, v; pb_unfold(d, n, t1, t2, u, v);
      const float r = sqrtf(u * u + v * v);
      if (r > reach) continue;
      const float cu = r > 1e-5f ? u / r : 1.0f, cv = r > 1e-5f ? v / r : 0.0f;
      if (r > pb_rim(b, cu, cv) * Rn) continue;
      // a little hue run from the core out, so a splat is not one flat chip
      const uint8_t h = (uint8_t)(b.hue + (int)(r / b.R * 14.0f));
      pb_put(paint, wet, (uint16_t)i, SEGMENT.color_from_palette(h, false, true, 0), 255);
    }

    if (sa < PB_SPLATMS) continue;

    // Landed: fling the droplets and set the runs going, then retire.
    const int nsat = 3 + hw_random8() % 4;
    for (int j = 0; j < nsat; j++) {
      const float ang = (float)hw_random16() * (6.2831853f / 65535.0f);
      const float dist = b.R * (1.25f + (float)hw_random8() * (0.8f / 255.0f));
      float px = b.x + (t1[0] * cosf(ang) + t2[0] * sinf(ang)) * dist;
      float py = b.y + (t1[1] * cosf(ang) + t2[1] * sinf(ang)) * dist;
      float pz = b.z + (t1[2] * cosf(ang) + t2[2] * sinf(ang)) * dist;
      pb_onto(cube, px, py, pz);
      pb_put(paint, wet, pb_plot(cube, cols, rows, B, rev, px, py, pz),
             SEGMENT.color_from_palette((uint8_t)(b.hue + 6), false, true, 0), 200);
    }
    // Drips: none at 0, up to three at full. They start on the rim, downhill.
    int nd = (drips * 4) / 256;                        // 0..3
    if (nd && hw_random8() < (uint8_t)((drips * 4) & 255)) nd++;
    if (nd > 3) nd = 3;
    float gx = 0, gy = 0, gz = cube ? -1.0f : 0.0f;
    if (!cube) gy = -1.0f;
    const float gn = gx * n[0] + gy * n[1] + gz * n[2];
    float dx = gx - gn * n[0], dy = gy - gn * n[1], dz = gz - gn * n[2];
    if (dx * dx + dy * dy + dz * dz < 1e-4f) { dx = b.x; dy = b.y; dz = 0.0f; }   // the lid: outwards
    { const float L = sqrtf(dx * dx + dy * dy + dz * dz);
      if (L > 1e-5f) { dx /= L; dy /= L; dz /= L; } else { dx = 1.0f; } }
    for (int j = 0; j < nd; j++) {
      int slot = -1;
      for (int q = 0; q < PB_MAXDRIP; q++) if (!s->drip[q].live) { slot = q; break; }
      if (slot < 0) break;
      PbDrip &dr = s->drip[slot];
      // spread across the downhill side of the rim
      const float side = ((float)hw_random8() * (1.4f / 255.0f) - 0.7f) * b.R;
      const float sx = dy * n[2] - dz * n[1], sy = dz * n[0] - dx * n[2], sz = dx * n[1] - dy * n[0];
      dr.x = b.x + dx * b.R * 0.5f + sx * side;
      dr.y = b.y + dy * b.R * 0.5f + sy * side;
      dr.z = b.z + dz * b.R * 0.5f + sz * side;
      pb_onto(cube, dr.x, dr.y, dr.z);
      dr.paint = 0.6f + (float)hw_random8() * (0.4f / 255.0f);
      dr.wob = (float)hw_random8() * 0.1f;
      dr.hue = b.hue; dr.live = 1;
    }
    s->lastBall = (uint8_t)k;
    b.live = 0;
  }

  // --- drips run ------------------------------------------------------------------------
  s->wobT += dts;
  for (int k = 0; k < PB_MAXDRIP; k++) {
    PbDrip &d = s->drip[k];
    if (!d.live) continue;
    float n[3], t1[3], t2[3];
    pb_frame(cube, d.x, d.y, d.z, n, t1, t2);
    float gx = 0, gy = cube ? 0.0f : -1.0f, gz = cube ? -1.0f : 0.0f;
    const float gn = gx * n[0] + gy * n[1] + gz * n[2];
    float vx = gx - gn * n[0], vy = gy - gn * n[1], vz = gz - gn * n[2];
    if (vx * vx + vy * vy + vz * vz < 1e-4f) { vx = d.x; vy = d.y; vz = 0.0f; }   // the lid: outwards
    float L = sqrtf(vx * vx + vy * vy + vz * vz);
    if (L < 1e-5f) { vx = 1.0f; L = 1.0f; }
    vx /= L; vy /= L; vz /= L;
    // a run wanders: a sideways sway, its own phase
    const float sxv = vy * n[2] - vz * n[1], syv = vz * n[0] - vx * n[2], szv = vx * n[1] - vy * n[0];
    const float sway = 0.35f * sinf(s->wobT * 5.0f + d.wob * 10.0f);
    const float sp = runSpeed * (0.35f + 0.65f * d.paint) * dts;
    const float ox = d.x, oy = d.y, oz = d.z;
    d.x += (vx + sxv * sway) * sp; d.y += (vy + syv * sway) * sp; d.z += (vz + szv * sway) * sp;
    pb_onto(cube, d.x, d.y, d.z);
    d.paint -= sp * 0.9f;

    const uint32_t c = SEGMENT.color_from_palette(d.hue, false, true, 0);
    // the trail, sub-stepped so a fast run is a line, not dots
    const float step = sqrtf((d.x - ox) * (d.x - ox) + (d.y - oy) * (d.y - oy) + (d.z - oz) * (d.z - oz));
    int sub = (int)(step * (float)(cube ? B : cols) * 0.5f) + 1;
    if (sub > 4) sub = 4;
    for (int j = 1; j <= sub; j++) {
      const float t = (float)j / (float)sub;
      pb_put(paint, wet, pb_plot(cube, cols, rows, B, rev, ox + (d.x - ox) * t, oy + (d.y - oy) * t, oz + (d.z - oz) * t),
             c, 90);
    }
    const bool offEdge = cube ? (d.z < -0.985f && !cfx_sixFaces) : (d.y < -0.985f);
    if (d.paint <= 0.0f || offEdge) {
      if (!offEdge) pb_put(paint, wet, pb_plot(cube, cols, rows, B, rev, d.x, d.y, d.z), c, 255);   // the bead
      d.live = 0;
    }
  }

  // --- treble spray around the newest splat -----------------------------------------------------
  {
    const PbBall &b = s->ball[s->lastBall];
    int sprays = (treb * dt) / 600;                    // ~10 a second at a strong treble
    if (sprays > 6) sprays = 6;
    if (treb > 60 && b.R > 0.0f) {
      float n[3], t1[3], t2[3];
      pb_frame(cube, b.x, b.y, b.z, n, t1, t2);
      for (int j = 0; j < sprays; j++) {
        const float ang = (float)hw_random16() * (6.2831853f / 65535.0f);
        const float dist = b.R * (0.6f + (float)hw_random8() * (2.4f / 255.0f));
        float px = b.x + (t1[0] * cosf(ang) + t2[0] * sinf(ang)) * dist;
        float py = b.y + (t1[1] * cosf(ang) + t2[1] * sinf(ang)) * dist;
        float pz = b.z + (t1[2] * cosf(ang) + t2[2] * sinf(ang)) * dist;
        pb_onto(cube, px, py, pz);
        pb_put(paint, wet, pb_plot(cube, cols, rows, B, rev, px, py, pz),
               mq_scale(SEGMENT.color_from_palette((uint8_t)(b.hue + 20), false, true, 0), 170), 120);
      }
    }
  }

  // --- present: the paint, its gloss, and the aim rings ---------------------------------------
  const uint8_t drive = cfx_drive(vol, 0.4f, 215);
  CFX_NET_PREP();
  for (int y = 0; y < rows; y++) {
    CFX_NET_ROW(y);
    for (int x = 0; x < cols; x++) {
      CFX_NET_SKIP(x);
      const size_t i = (size_t)cfx_cidx(x, y, cols, B, cube);
      int r = paint[i * 3], g = paint[i * 3 + 1], bl = paint[i * 3 + 2];
      if (sheenOn && wet[i]) {                          // wet paint is glossy: a white lift that dries off
        const int w = (wet[i] * 90) >> 8;
        r += w; g += w; bl += w;
      }
      // an aim ring shrinking onto where a ball is about to land
      for (int k = 0; k < PB_MAXBALL; k++) {
        const PbBall &b = s->ball[k];
        if (!b.live || b.age >= b.aim) continue;
        const float px = pos[i * 3] * (1.0f / 127.0f), py = pos[i * 3 + 1] * (1.0f / 127.0f),
                    pz = pos[i * 3 + 2] * (1.0f / 127.0f);
        const float dd = sqrtf((px - b.x) * (px - b.x) + (py - b.y) * (py - b.y) + (pz - b.z) * (pz - b.z));
        const float a = (float)b.age / (float)b.aim;
        const float ring = b.R * (2.2f - 2.0f * a);
        const float px1 = 2.0f / (float)(cube ? B : cols);
        if (fabsf(dd - ring) < px1) {
          const uint32_t c = SEGMENT.color_from_palette(b.hue, false, true, 0);
          const int w = (int)(60.0f + 140.0f * a);
          r += (((c >> 16) & 255) * w) >> 8; g += (((c >> 8) & 255) * w) >> 8; bl += ((c & 255) * w) >> 8;
        }
      }
      if (r > 255) r = 255; if (g > 255) g = 255; if (bl > 255) bl = 255;
      SEGMENT.setPixelColorXY(x, y, mq_scale(RGBW32(r, g, bl, 0), drive));
    }
  }
  FX_DONE;
}

static const char _data_FX_MODE_PAINTBALL[] PROGMEM =
  "Ace 3-D Paintball@Drip speed,Splat size,Fire rate,Drips,Dry time,Beat volleys,Wet shine,Flat mode;;!;2f;sx=110,ix=165,c1=115,c2=150,c3=19,o1=1,o2=1,pal=6";
// AI: end


// ---------------------------------------------------------------------------
// Registration - joins the effect bank, which decides whether this effect
// claims one of the device's limited effect slots. See cube_fx_bank.h.
// ---------------------------------------------------------------------------
static CfxBankReg cube_fx_52_paintball_reg(&mode_paintball, _data_FX_MODE_PAINTBALL);
