"""The studio's sound sent to WLED devices as audioreactive's Audio Sync: the
studio's analysis (the synth, a capture or an audio file - what the effects
here hear) in the v2 packet any WLED with audioreactive set to Receive takes,
so stock devices on the network move to the studio's music too.

    tx = AudioSyncSender("multicast")      # or "broadcast", or "unicast" with host=
    tx.send(eng)                           # each frame: at most one packet per PERIOD
    tx.close()

The packet is audioreactive's `audioSyncPacket` (usermods/audioreactive/
audio_reactive.cpp): 44 bytes, little-endian, header "00002". It goes to
239.0.0.1:11988 as the device itself sends it (multicast, one hop), or to
the subnet's broadcast address (where multicast is filtered; upstream adds
broadcast as a sync transport too, wled/WLED#5863), or straight to one
device. A device listens on the port whatever address the packet came to.
"""
# AI: below section was generated by an AI
import socket
import struct
import time

import numpy as np

PORT = 11988                      # audioreactive's default audioSyncPort
GROUP = "239.0.0.1"               # its multicast group
HEADER = b"00002\x00"             # UDP_SYNC_HEADER, with its terminating zero: char header[6]
PERIOD = 0.02                     # seconds between packets: the device's own sender runs at about this rate
MODES = ("off", "multicast", "broadcast", "unicast")

# header[6], reserved1[2], sampleRaw, sampleSmth, samplePeak, reserved2, fftResult[16], reserved3, FFT_Magnitude, FFT_MajorPeak
LAYOUT = struct.Struct("<6s2xffBB16sHff")
assert LAYOUT.size == 44


def packet(volume, raw, peak, fft, magnitude, major_peak):
    """The v2 packet's bytes. volume / raw: the smoothed and raw level (0..255 as the effects read them);
    peak: a beat now; fft: the sixteen GEQ channels (0..255 - the device sends at most 254); magnitude and
    major_peak: the loudest frequency's strength and Hz."""
    bins = bytes(int(min(254, max(0, b))) for b in np.asarray(fft, np.float64)[:16])
    bins = bins.ljust(16, b"\x00")
    return LAYOUT.pack(HEADER, float(max(0.0, raw)), float(max(0.0, volume)), 1 if peak else 0, 0, bins, 0,
                       float(max(0.0, magnitude)), float(max(0.0, major_peak)))


def unpack(data):
    """A packet back as a dict (the tests, and a check of what was sent)."""
    h, raw, smth, peak, _r2, bins, _r3, mag, major = LAYOUT.unpack(data[:LAYOUT.size])
    return {"header": h, "raw": raw, "volume": smth, "peak": peak, "fft": list(bins), "magnitude": mag, "major_peak": major}


class AudioSyncSender:
    """Packets from the engine's audio as it is now, rate-limited; `sent` counts them, `error` says why one failed."""

    def __init__(self, mode="multicast", host=None, port=PORT):
        if mode not in MODES[1:]:
            raise ValueError(f"unknown audio sync mode {mode!r}")
        if mode == "unicast" and not host:
            raise ValueError("unicast audio sync needs a device")
        self.mode, self.port = mode, int(port)
        self.addr = {"multicast": GROUP, "broadcast": "255.255.255.255"}.get(mode) or _host_only(host)
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        if mode == "multicast":
            self.sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 1)   # the local network only
        elif mode == "broadcast":
            self.sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        self.sent, self.error, self._last, self._peak_held = 0, None, 0.0, False

    def describe(self):
        to = {"multicast": f"multicast {GROUP}", "broadcast": "broadcast"}.get(self.mode, self.addr)
        return f"sending to {to}:{self.port} - {self.sent} packets" + (f" ({self.error})" if self.error else "")

    def send(self, eng, now=None):
        """One packet from `eng` (its last_audio, fft, last_peak) unless one went less than PERIOD ago; a beat
        between two packets is held for the next, so none is lost to the rate. True when a packet went."""
        vol, peak = getattr(eng, "last_audio", (0.0, 0))
        self._peak_held = self._peak_held or bool(peak)
        now = time.perf_counter() if now is None else now
        if now - self._last < PERIOD:
            return False
        freq, mag = getattr(eng, "last_peak", (0.0, 0.0))
        data = packet(vol, vol, self._peak_held, eng.fft, mag, freq)
        try:
            self.sock.sendto(data, (self.addr, self.port))
            self.sent += 1
            self.error = None
        except OSError as e:                            # no network, a host gone: said, and tried again next time
            self.error = str(e)
            return False
        finally:
            self._last = now
        self._peak_held = False
        return True

    def close(self):
        try:
            self.sock.close()
        except OSError:
            pass


def _host_only(host):
    """A device as the studio keeps it ("http://10.0.0.5", "10.0.0.5:80") down to the address."""
    h = str(host).strip()
    h = h.split("://", 1)[-1].split("/", 1)[0]
    return h.rsplit(":", 1)[0] if h.count(":") == 1 else h
# AI: end
