"""Live video for the Video node: a webcam, a video file, or a built-in test
pattern, decoded to small RGB frames the engine's video slot takes
(Engine.video). Video plays only in the studio; it reaches the LEDs by the
stream (Device > Stream), which sends the sim's picture as it is.

    src = video.open_source("file", path="clip.mp4", width=96, loop=True)
    src = video.open_source("webcam", name="Integrated Camera")
    src = video.open_source("test")              # no ffmpeg needed
    frame, n = src.latest()                      # (h, w, 3) uint8 and its number, or (None, 0)
    src.close()

Files and webcams are read by ffmpeg (it must be on the PATH, as for the
camera map): every frame scaled and cropped to `width` x `height` (16:9 by
default, filling the frame - no black bars on the LEDs), in a thread that
keeps only the newest, so a slow frame in the studio never makes the video
lag. A file plays at its own speed and, with loop, round again.
"""
# AI: below section was generated by an AI
import math
import re
import shutil
import subprocess
import sys
import threading
import time

import numpy as np

WIDTH, HEIGHT = 96, 54          # the decoded frame: enough for any LED shape, small enough to copy every frame


def ffmpeg():
    return shutil.which("ffmpeg")


class TestPattern:
    """A moving picture with no ffmpeg: colour bars drifting, a bright disc going round and a pulse - enough
    to see a projection and a style work. Frames come from the clock, so it never stalls."""
    kind = "test"

    def __init__(self, width=WIDTH, height=HEIGHT):
        self.w, self.h = int(width), int(height)
        self.t0 = time.time()
        self.paused_at = None
        self.n = 0
        self._last = None
        self.error = None
        yy, xx = np.mgrid[0:self.h, 0:self.w]
        self._x = xx / max(1, self.w - 1)
        self._y = yy / max(1, self.h - 1)

    def describe(self):
        return f"test pattern, {self.w} x {self.h}"

    def frame_at(self, t):
        x, y = self._x, self._y
        hue = (x + t * 0.08) % 1.0
        r = np.clip(np.abs(hue * 6 - 3) - 1, 0, 1)
        g = np.clip(2 - np.abs(hue * 6 - 2), 0, 1)
        b = np.clip(2 - np.abs(hue * 6 - 4), 0, 1)
        shade = 0.25 + 0.35 * (1 - y)                          # dim bars, so the disc stands out
        cx, cy = 0.5 + 0.3 * math.cos(t * 0.9), 0.5 + 0.3 * math.sin(t * 0.9)
        d = np.hypot((x - cx) * self.w / self.h, y - cy)
        disc = np.clip((0.22 - d) * 20, 0, 1)                    # a soft white disc going round
        pulse = 0.5 + 0.5 * math.sin(t * 3.0)
        rgb = np.stack([r, g, b], -1) * shade[..., None]
        rgb = rgb * (1 - disc[..., None]) + disc[..., None] * (0.6 + 0.4 * pulse)
        return (np.clip(rgb, 0, 1) * 255).astype(np.uint8)

    def latest(self):
        t = (self.paused_at if self.paused_at is not None else time.time()) - self.t0
        if self.paused_at is None or self._last is None:
            self._last = self.frame_at(t)
            self.n += 1
        return self._last, self.n

    def pause(self, on=True):
        if on and self.paused_at is None:
            self.paused_at = time.time()
        elif not on and self.paused_at is not None:
            self.t0 += time.time() - self.paused_at
            self.paused_at = None

    @property
    def paused(self):
        return self.paused_at is not None

    def close(self):
        pass


class FfmpegSource:
    """A file or a webcam through ffmpeg, frames read on a thread; latest() is the newest decoded."""

    def __init__(self, input_args, label, kind, width=WIDTH, height=HEIGHT, realtime=True, loop=False, fit=False):
        self.kind, self.label = kind, label
        self.w, self.h = int(width), int(height) // 2 * 2
        self.error = None
        self.n = 0
        self._frame = None
        self._paused = False
        self._stop = threading.Event()
        exe = ffmpeg()
        if not exe:
            raise ValueError("video needs ffmpeg on the PATH (ffmpeg.org) - the test pattern works without it")
        pre = (["-re"] if realtime else []) + (["-stream_loop", "-1"] if loop else [])
        if fit:                                                  # all of the picture, bars where it is narrower (mapping)
            vf = f"scale={self.w}:{self.h}:force_original_aspect_ratio=decrease,pad={self.w}:{self.h}:(ow-iw)/2:(oh-ih)/2"
        else:                                                    # the frame filled (the LEDs: no black bars)
            vf = f"scale={self.w}:{self.h}:force_original_aspect_ratio=increase,crop={self.w}:{self.h}"
        self.cmd = [exe, "-v", "error", "-nostdin"] + pre + list(input_args) + ["-vf", vf, "-an", "-f", "rawvideo", "-pix_fmt", "rgb24", "-"]
        from native import procs
        self.proc = procs.popen(self.cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        self.thread = threading.Thread(target=self._read, daemon=True)
        self.thread.start()

    def describe(self):
        return f"{self.label}, {self.w} x {self.h}"

    def _read(self):
        size = self.w * self.h * 3
        out = self.proc.stdout
        try:
            while not self._stop.is_set():
                buf = out.read(size)
                if len(buf) < size:
                    break
                if not self._paused:                         # paused: the picture holds (the video runs on)
                    self._frame = np.frombuffer(buf, np.uint8).reshape(self.h, self.w, 3)
                    self.n += 1
        except Exception as e:
            self.error = str(e)
        if not self._stop.is_set() and self.error is None:
            try:
                err = self.proc.stderr.read().decode("utf-8", "replace").strip()
            except Exception:
                err = ""
            self.error = (err.splitlines()[-1] if err else "the video ended")

    def latest(self):
        return self._frame, self.n

    def pause(self, on=True):
        self._paused = bool(on)

    @property
    def paused(self):
        return self._paused

    def close(self):
        self._stop.set()
        try:
            self.proc.kill()
        except Exception:
            pass


def webcams():
    """The cameras ffmpeg can open here: [(name shown, input args)]."""
    exe = ffmpeg()
    if not exe:
        return []
    from native import procs
    out = []
    try:
        if sys.platform == "win32":
            txt = procs.run([exe, "-hide_banner", "-list_devices", "true", "-f", "dshow", "-i", "dummy"],
                            capture_output=True, text=True, timeout=15).stderr
            for m in re.finditer(r'"([^"]+)"\s*\(video\)', txt):
                out.append((m.group(1), ["-f", "dshow", "-i", f"video={m.group(1)}"]))
        elif sys.platform == "darwin":
            txt = procs.run([exe, "-hide_banner", "-f", "avfoundation", "-list_devices", "true", "-i", ""],
                            capture_output=True, text=True, timeout=15).stderr
            video = txt.split("audio devices")[0]
            for m in re.finditer(r"\[(\d+)\]\s+(.+)", video):
                if "Capture screen" not in m.group(2):
                    out.append((m.group(2).strip(), ["-f", "avfoundation", "-framerate", "30", "-i", m.group(1)]))
        else:
            import glob
            for dev in sorted(glob.glob("/dev/video*")):
                out.append((dev, ["-f", "v4l2", "-i", dev]))
    except Exception:
        pass
    return out


def open_source(kind, path=None, name=None, width=WIDTH, height=HEIGHT, loop=True, fit=False):
    """A video source: kind "test", "file" (path) or "webcam" (name, from webcams())."""
    if kind == "test":
        return TestPattern(width, height)
    if kind == "file":
        import os
        if not path or not os.path.exists(path):
            raise ValueError(f"no video file at {path}")
        return FfmpegSource(["-i", path], os.path.basename(path), "file", width, height, realtime=True, loop=loop)
    if kind == "webcam":
        cams = dict(webcams())
        if name not in cams:
            raise ValueError(f"no camera called {name!r}" + (f" - there is {', '.join(cams)}" if cams else " - none found"))
        return FfmpegSource(cams[name], name, "webcam", width, height, realtime=False, fit=fit)
    raise ValueError(f"unknown video source {kind!r}")
# AI: end
