"""The side panel's VIDEO section: where the Video node's picture comes from -
a webcam, a video file, or the test pattern - its size, play and pause,
and a little preview. Each engine frame the newest video frame goes into
the engine's video slot (push, from App.audio_push). The choices are kept
in the project (options["video"]); nothing starts by itself when a project
opens - a camera is never switched on unasked.

    video_ui.build(app)          # inside the panel's Section
    video_ui.start(app, "test")  # or "file", "webcam" - the panel's Play
    video_ui.push(app)           # each engine frame
    video_ui.stop(app)
"""
# AI: below section was generated by an AI
import atexit
import os

import dearpygui.dearpygui as dpg

from native import form, video
from native.typeface import px

KINDS = (("none", "none"), ("test", "test pattern"), ("file", "a video file"), ("webcam", "a webcam"))
EXTS = (".mp4", ".mov", ".mkv", ".webm", ".avi", ".m4v", ".gif", ".mpg")
PREVIEW_W, PREVIEW_H = video.WIDTH, video.HEIGHT


def _opts(app):
    o = app.project.options.setdefault("video", {})
    o.setdefault("kind", "test")
    o.setdefault("width", video.WIDTH)
    o.setdefault("loop", True)
    return o


def build(app):
    o = _opts(app)
    names = [n for _, n in KINDS]
    with form.row("source", tip="where the Video node's picture comes from"):
        dpg.add_combo(names, tag="video_kind", width=-1, default_value=dict(KINDS).get(o["kind"], names[1]),
                      callback=lambda s, v: _set_kind(app, v))
    with form.row("file", tag="video_file_row"):
        dpg.add_input_text(tag="video_path", width=-px(70), default_value=o.get("path", ""), hint="a video file",
                           on_enter=True, callback=lambda s, v: _set(app, "path", v))
        dpg.add_button(label="Choose...", tag="video_choose", callback=lambda: dpg.show_item("video_dialog"))
        _tip("a video file: mp4, mov, mkv, webm, avi, gif - read by ffmpeg")
    with form.row("camera", tag="video_cam_row"):
        dpg.add_combo([o.get("name", "")] if o.get("name") else [], tag="video_cam", width=-px(70),
                      default_value=o.get("name", ""), callback=lambda s, v: _set(app, "name", v))
        dpg.add_button(label="Find", tag="video_find", callback=lambda: find_cameras(app))
        _tip("the webcams ffmpeg can open on this computer, into the list")
    with dpg.file_dialog(directory_selector=False, show=False, tag="video_dialog", width=px(620), height=px(420),
                         callback=lambda s, a: _chosen(app, a.get("file_path_name", ""))):
        dpg.add_file_extension("{" + ",".join(EXTS) + "}", color=(120, 200, 120))
        dpg.add_file_extension(".*")
    form.check("loop the file", tag="video_loop", default_value=bool(o["loop"]), callback=lambda s, v: _set(app, "loop", bool(v)))
    dpg.add_group(tag="video_size_row")
    app.pair("video_size_row", "video_width", "size", int(o["width"]), 32, 256,
             lambda v: _set(app, "width", int(v)), unit="px")
    with form.under():
        dpg.add_button(label="Play", tag="video_play", callback=lambda: toggle(app))
        _tip("play the source into the Video node; again: pause (the picture holds)")
        dpg.add_button(label="Stop", tag="video_stop", callback=lambda: stop(app))
        _tip("the source closed (a webcam switched off); the Video node goes black")
    from native.textures import registry
    if not dpg.does_item_exist("video_tex"):
        dpg.add_dynamic_texture(PREVIEW_W, PREVIEW_H, [0.0] * (PREVIEW_W * PREVIEW_H * 4), tag="video_tex", parent=registry())
    with form.under():
        dpg.add_image("video_tex", width=px(PREVIEW_W * 2), height=px(PREVIEW_H * 2), tag="video_preview")
    dpg.add_text("", tag="video_msg", wrap=0)
    _show_rows(app)
    _words(app)


def _tip(text):
    from native import chrome
    chrome.tip(text)


def _set(app, k, v):
    _opts(app)[k] = v
    app.project.save()


def _set_kind(app, words):
    kind = next((k for k, n in KINDS if n == words), "none")
    _set(app, "kind", kind)
    _show_rows(app)
    if getattr(app, "video_src", None) is not None:
        start(app)                                   # playing: the new source at once


def _show_rows(app):
    kind = _opts(app)["kind"]
    if dpg.does_item_exist("video_file_row"):
        dpg.configure_item("video_file_row", show=kind == "file")
        dpg.configure_item("video_loop", show=kind == "file")
        dpg.configure_item("video_cam_row", show=kind == "webcam")


def _chosen(app, path):
    if path:
        dpg.set_value("video_path", path)
        _set(app, "path", path)
        if getattr(app, "video_src", None) is not None:
            start(app)


def find_cameras(app):
    """The webcams ffmpeg can open, into the camera list."""
    cams = [n for n, _ in video.webcams()]
    dpg.configure_item("video_cam", items=cams)
    if cams and dpg.get_value("video_cam") not in cams:
        dpg.set_value("video_cam", cams[0]); _set(app, "name", cams[0])
    _words(app, f"{len(cams)} camera(s) found" if cams else
           ("no camera found" if video.ffmpeg() else "a webcam needs ffmpeg on the PATH (ffmpeg.org)"))
    return cams


def start(app, kind=None):
    """Play the chosen source (or `kind`); the one playing before is closed. False, with the reason
    in the panel, when it cannot be opened."""
    o = _opts(app)
    if kind:
        o["kind"] = kind
        if dpg.does_item_exist("video_kind"):
            dpg.set_value("video_kind", dict(KINDS)[kind])
            _show_rows(app)
    stop(app, quiet=True)
    if o["kind"] == "none":
        _words(app); return False
    w = int(o["width"]); h = max(2, int(round(w * 9 / 16)) // 2 * 2)
    try:
        app.video_src = video.open_source(o["kind"], path=o.get("path"), name=o.get("name"), width=w, height=h,
                                          loop=bool(o["loop"]))
    except Exception as e:
        app.video_src = None
        _words(app, str(e)); app.gp.status(f"video: {e}", "warn")
        return False
    app._video_n = -1
    atexit.register(app.video_src.close)
    _words(app)
    return True


def toggle(app):
    """Play, or pause (the picture holds), or play on."""
    src = getattr(app, "video_src", None)
    if src is None:
        return start(app)
    src.pause(not src.paused)
    _words(app)
    return True


def stop(app, quiet=False):
    src = getattr(app, "video_src", None)
    if src is not None:
        src.close()
    app.video_src = None
    app.eng.video(None)
    if not quiet:
        _words(app)


def push(app):
    """The newest frame into the engine's video slot, once per new frame; a source that failed is stopped."""
    src = getattr(app, "video_src", None)
    if src is None:
        return
    frame, n = src.latest()
    if frame is not None and n != getattr(app, "_video_n", -1):
        app._video_n = n
        app.eng.video(frame)
        _preview(frame)
    err = getattr(src, "error", None)
    if err:                                          # ffmpeg ended (the file's end without loop, a camera gone, an error)
        stop(app, quiet=True)
        _words(app, f"stopped: {err}")


def _preview(frame):
    """The frame in the panel, at the preview's size (nearest pixels: it is a glance, not the picture)."""
    import numpy as np
    if not dpg.does_item_exist("video_tex") or not dpg.is_item_visible("video_preview"):
        return
    h, w = frame.shape[:2]
    ys = (np.arange(PREVIEW_H) * h // PREVIEW_H).clip(0, h - 1)
    xs = (np.arange(PREVIEW_W) * w // PREVIEW_W).clip(0, w - 1)
    small = frame[ys][:, xs]
    rgba = np.concatenate([small.astype(np.float32) / 255.0, np.ones((PREVIEW_H, PREVIEW_W, 1), np.float32)], -1)
    dpg.set_value("video_tex", rgba.ravel())


def _words(app, extra=None):
    if not dpg.does_item_exist("video_msg"):
        return
    src = getattr(app, "video_src", None)
    if src is not None:
        state = ("paused - " if src.paused else "playing - ") + src.describe()
    else:
        state = "stopped"
    tail = " The Video node shows it; Device > Stream sends the picture to the LEDs (video cannot play on the device by itself)."
    if not video.ffmpeg() and _opts(app)["kind"] in ("file", "webcam"):
        tail += " Files and webcams need ffmpeg on the PATH (ffmpeg.org)."
    dpg.set_value("video_msg", (extra + " - " if extra else "") + state + "." + tail)
    if dpg.does_item_exist("video_play"):
        dpg.configure_item("video_play", label="Pause" if src is not None and not src.paused else "Play")
# AI: end
